Repository phalcon/cphalcon, pull requests merged in 2018-10, with the labels that each got.

#13533 [#13529] - Moved the sharedLock in the dialects. PostgreSql and Sqlit…
  phalcon/db/dialect.zep
  phalcon/db/dialect/mysql.zep
  phalcon/db/dialect/postgresql.zep
  phalcon/db/dialect/sqlite.zep
Labels: Bug - Medium

#13532 [#13529] - Moved the sharedLock in the dialects. PostgreSql and Sqlit…
  phalcon/db/dialect.zep
  phalcon/db/dialect/mysql.zep
  phalcon/db/dialect/postgresql.zep
  phalcon/db/dialect/sqlite.zep
Labels: Bug - Medium

#13530 T13445 ability to change the flash html template
  CHANGELOG-4.0.md
  phalcon/flash.zep
  phalcon/flashinterface.zep
  tests/unit/Flash/SessionTest.php
Labels: New Feature Request

#13536 [#13468] - Added `getHandlerSuffix()`, `setHandlerSuffix()` in Dispatcher
  CHANGELOG-4.0.md
  phalcon/cli/dispatcher.zep
  phalcon/cli/dispatcherinterface.zep
  phalcon/dispatcher.zep
  phalcon/dispatcherinterface.zep
Labels: Breaks BC, Bug - Medium, Enhancement

#12251 Renamed notSave event to notSaved in Collection.
  phalcon/mvc/collection.zep
Labels: Breaks BC, Mongo, RFC
