Repository phalcon/cphalcon, pull requests merged in 2018-12, with the labels that each got.

#13562 [#13543] Add more pdo types
  .travis.yml
  CHANGELOG-4.0.md
  phalcon/db/adapter/pdo.zep
  phalcon/db/adapter/pdo/mysql.zep
  phalcon/db/adapter/pdo/postgresql.zep
  phalcon/db/adapter/pdo/sqlite.zep
  phalcon/db/column.zep
  phalcon/db/columninterface.zep
  phalcon/db/dialect.zep
  phalcon/db/dialect/mysql.zep
  phalcon/db/dialect/postgresql.zep
  phalcon/db/dialect/sqlite.zep
  phalcon/mvc/model/metadata/strategy/annotations.zep
  tests/README.md
  tests/_bootstrap.php
  tests/_ci/setup-dbs.sh
  tests/_data/schemas/phalcon-schema-mysql.sql
  tests/_data/schemas/phalcon-schema-postgresql.sql
  tests/_data/schemas/phalcon-schema-sqlite-translations.sql
  tests/_data/schemas/phalcon-schema-sqlite.sql
  tests/_data/schemas/postgresql/phalcon_test.sql
  tests/_support/Helper/Db/Adapter/Pdo/MysqlTrait.php
  tests/_support/Helper/Db/Adapter/Pdo/PostgresqlTrait.php
  tests/unit.suite.yml
  tests/unit/Db/Adapter/Pdo/ColumnsBase.php
  tests/unit/Db/Adapter/Pdo/Mysql/ColumnsCest.php
  tests/unit/Db/Adapter/Pdo/Mysql/TablesCest.php
  tests/unit/Db/Adapter/Pdo/MysqlTest.php
  tests/unit/Db/Adapter/Pdo/Postgresql/ColumnsCest.php
  tests/unit/Db/Adapter/Pdo/Postgresql/TablesCest.php
  tests/unit/Db/Adapter/Pdo/PostgresqlTest.php
  tests/unit/Db/Adapter/Pdo/TablesBase.php
  tests/unit/Db/ColumnCest.php
  tests/unit/Db/ColumnTest.php
  tests/unit/VersionTest.php
  unit-tests/DbDescribeTest.php
Labels: Feature

#13651 [#13491] - Corrected interfaces
  phalcon/validation/validator/alnum.zep
  phalcon/validation/validator/alpha.zep
  phalcon/validation/validator/between.zep
  phalcon/validation/validator/callback.zep
  phalcon/validation/validator/confirmation.zep
  phalcon/validation/validator/creditcard.zep
  phalcon/validation/validator/date.zep
  phalcon/validation/validator/digit.zep
  phalcon/validation/validator/email.zep
  phalcon/validation/validator/exclusionin.zep
  phalcon/validation/validator/file.zep
  phalcon/validation/validator/identical.zep
  phalcon/validation/validator/inclusionin.zep
  phalcon/validation/validator/numericality.zep
  phalcon/validation/validator/presenceof.zep
  phalcon/validation/validator/regex.zep
  phalcon/validation/validator/stringlength.zep
  phalcon/validation/validator/url.zep
  phalcon/validation/validatorinterface.zep
Labels: Bug - Low

#13671 Update the nanobox config to mongo 4.0
  tests/_ci/nanobox/boxfile.7.2.yml
  tests/_ci/nanobox/boxfile.7.3.yml
Labels: Enhancement, Mongo

#13678 [4.0.x] - Another correction to the test
  tests/integration/Paginator/Adapter/QueryBuilderCest.php
Labels: Bug - Medium

#13708 Optimezed logger test
  tests/_data/fixtures/Traits/LoggerTrait.php
Labels: Enhancement, Testing
