Repository phalcon/cphalcon, pull requests merged in 2019-09, with the labels that each got.

#14363 Check gd extension when test Phalcon
  .travis.yml
  composer.json
  tests/_data/fixtures/Traits/GdTrait.php
  tests/unit/Image/Adapter/Gd/GetHeightCest.php
  tests/unit/Image/Adapter/Gd/GetMimeCest.php
  tests/unit/Image/Adapter/Gd/GetVersionCest.php
  tests/unit/Image/Adapter/Gd/GetWidthCest.php
Labels: Testing

#14385 Issue 14374
  tests/unit/Di/SetCest.php
Labels: Testing

#14387 Issue 14386
  CHANGELOG-4.0.md
  phalcon/Mvc/Model.zep
  phalcon/Mvc/ModelInterface.zep
Labels: 4.0, Enhancement

#14395 T14394 3rdparty 1
  3rdparty/licenses/LICENSE-ATLAS.txt
  3rdparty/licenses/LICENSE-AURA.txt
  3rdparty/licenses/LICENSE-DIACTOROS.txt
  3rdparty/licenses/LICENSE-PHP.txt
  3rdparty/licenses/LICENSE-ZEND.txt
  README.md
Labels: 4.0, Enhancement

#14410 Volt: Corrected syntax recognize for "set" and "is" keywords
  .ci/run-volt-tests.sh
  CHANGELOG-4.0.md
  ext/phalcon/mvc/view/engine/volt/base.c
  ext/phalcon/mvc/view/engine/volt/lemon.c
  ext/phalcon/mvc/view/engine/volt/parser.c
  ext/phalcon/mvc/view/engine/volt/parser.php7.c
  ext/phalcon/mvc/view/engine/volt/parser.php7.lemon
  ext/phalcon/mvc/view/engine/volt/scanner.c
  ext/phalcon/mvc/view/engine/volt/scanner.h
  ext/phalcon/mvc/view/engine/volt/scanner.re
  ext/phalcon/mvc/view/engine/volt/volt.h
  tests/integration/Mvc/View/Engine/Volt/Compiler/ParseCest.php
  tests/syntax/volt/statements/is/001.phpt
  tests/syntax/volt/statements/is/002.phpt
  tests/syntax/volt/statements/is/bug14288.phpt
  tests/syntax/volt/statements/set/001.phpt
  tests/syntax/volt/statements/set/bug14288.phpt
Labels: 4.0

#14421 Form attributes fixed
  CHANGELOG-4.0.md
  phalcon/Forms/Form.zep
Labels: 4.0, Bug - Low

#14422 Fixed 'NOT BETWEEN' support in PHQL
  .ci/genparsers.sh
  .travis.yml
  CHANGELOG-4.0.md
  ext/phalcon/acl/adapter/memory.zep.c
  ext/phalcon/annotations/annotation.zep.c
  ext/phalcon/annotations/parser.c
  ext/phalcon/annotations/parser.php7.c
  ext/phalcon/annotations/parser.php7.lemon
  ext/phalcon/application/abstractapplication.zep.c
  ext/phalcon/application/abstractapplication.zep.h
  ext/phalcon/cache/adapterfactory.zep.h
  ext/phalcon/cache/cachefactory.zep.h
  ext/phalcon/cli/router.zep.c
  ext/phalcon/cli/router.zep.h
  ext/phalcon/dispatcher/abstractdispatcher.zep.h
  ext/phalcon/factory/abstractfactory.zep.c
  ext/phalcon/filter.zep.c
  ext/phalcon/filter/filterfactory.zep.h
  ext/phalcon/firewall/adapter/acl.zep.h
  ext/phalcon/firewall/adapter/annotations.zep.h
  ext/phalcon/forms/element/select.zep.c
  ext/phalcon/forms/element/select.zep.h
  ext/phalcon/forms/form.zep.c
  ext/phalcon/forms/manager.zep.h
  ext/phalcon/helper/fs.zep.c
  ext/phalcon/image/adapter/imagick.zep.c
  ext/phalcon/logger/adapterfactory.zep.c
  ext/phalcon/logger/adapterfactory.zep.h
  ext/phalcon/mvc/model.zep.c
  ext/phalcon/mvc/model/query.zep.c
  ext/phalcon/mvc/model/query.zep.h
  ext/phalcon/mvc/model/query/base.c
  ext/phalcon/mvc/model/query/lang.zep.c
  ext/phalcon/mvc/model/query/lang.zep.h
  ext/phalcon/mvc/model/query/parser.c
  ext/phalcon/mvc/model/query/parser.php7.c
  ext/phalcon/mvc/model/query/parser.php7.h
  ext/phalcon/mvc/model/query/parser.php7.lemon
  ext/phalcon/mvc/model/query/scanner.c
  ext/phalcon/mvc/model/query/scanner.h
  ext/phalcon/mvc/model/query/scanner.re
  ext/phalcon/mvc/model/resultset/simple.zep.c
  ext/phalcon/mvc/model/resultset/simple.zep.h
  ext/phalcon/paginator/adapter/abstractadapter.zep.c
  ext/phalcon/paginator/adapter/abstractadapter.zep.h
  ext/phalcon/translate/translatefactory.zep.c
  ext/phalcon/translate/translatefactory.zep.h
  ext/phalcon/validation/validator/file/size/equal.zep.c
  ext/phalcon/validation/validator/file/size/max.zep.c
  ext/phalcon/validation/validator/file/size/min.zep.c
  phalcon/Mvc/Model/Query.zep
  phalcon/Mvc/Model/Query/Lang.zep
  tests/run-syntax-tests.sh
  tests/syntax/phql/001.phpt
  tests/syntax/phql/002.phpt
  tests/syntax/phql/bu14253.phpt
Labels: 4.0, Bug - Low, Docs needed

#14434 T14432 serverrequest protocol
  CHANGELOG-4.0.md
  phalcon/Http/Message/ServerRequestFactory.zep
  tests/unit/Http/Message/ServerRequestFactory/LoadCest.php
Labels: 4.0, Bug - Medium

#14439 T14426 - Correction for the protocol
  phalcon/Http/Message/ServerRequestFactory.zep
  tests/unit/Http/Message/ServerRequestFactory/LoadCest.php
Labels: 4.0, Bug - High
