Repository phalcon/cphalcon, pull requests merged in 2019-03, with the labels that each got.

#13862 Pdo radicaloptions
  phalcon/db/adapter/pdo.zep
  phalcon/db/adapter/pdo/mysql.zep
  phalcon/db/adapter/pdo/postgresql.zep
  phalcon/db/adapter/pdo/sqlite.zep
Labels: Enhancement

#13877 [Translate] more options to csv adapter
  CHANGELOG-4.0.md
  phalcon/translate/adapter/csv.zep
  tests/_data/assets/translation/csv/fr_FR_options.csv
  tests/unit/Translate/Adapter/CsvCest.php
Labels: Feature

#13891 T13886 collection
  CHANGELOG-4.0.md
  phalcon/collection.zep
  tests/unit/Collection/ClearCest.php
  tests/unit/Collection/ConstructCest.php
  tests/unit/Collection/CountCest.php
  tests/unit/Collection/GetCest.php
  tests/unit/Collection/GetIteratorCest.php
  tests/unit/Collection/HasCest.php
  tests/unit/Collection/InitCest.php
  tests/unit/Collection/JsonSerializeCest.php
  tests/unit/Collection/RemoveCest.php
  tests/unit/Collection/SerializeCest.php
  tests/unit/Collection/SetCest.php
  tests/unit/Collection/ToArrayCest.php
  tests/unit/Collection/ToJsonCest.php
  tests/unit/Collection/UnserializeCest.php
Labels: Feature - NFR

#13894 Fix: assets manager hard reference to phalcon\tag. Use DI
  CHANGELOG-4.0.md
  phalcon/assets/manager.zep
  tests/_data/fixtures/Assets/CustomTag.php
  tests/unit/Assets/Manager/OutputCssCest.php
  tests/unit/Assets/Manager/OutputJsCest.php
Labels: Bug - Medium

#13898 T13897 remove collections
  phalcon/collection.zep
  phalcon/registry.zep
  phalcon/session/bag.zep
  tests/integration/Session/Bag/RemoveCest.php
  tests/unit/Collection/RemoveCest.php
  tests/unit/Registry/RemoveCest.php
Labels: Breaks BC, Enhancement
