Repository phalcon/cphalcon, pull requests merged in 2019-06, with the labels that each got.

#14149 `Phalcon\Di\FactoryDefault\Cli` can now use the new Filter system.
  CHANGELOG-4.0.md
  phalcon/Di/FactoryDefault.zep
  phalcon/Di/FactoryDefault/Cli.zep
  tests/cli/Di/FactoryDefault/Cli/ConstructCest.php
  tests/unit/Di/FactoryDefault/ConstructCest.php
Labels: Enhancement

#14120 Added sasl authentication
  CHANGELOG-4.0.md
  phalcon/Storage/Adapter/Libmemcached.zep
Labels: Docs needed, Enhancement

#14197 Fixed lower cases
  phalcon/Validation/Validator/File.zep
Labels: 4.0, Bug - Low
