Repository phalcon/cphalcon, pull requests merged in 2019-02, with the labels that each got.

#13805 Updated CFLAG default build param
  build/install
Labels: Bug - Low

#13830 Allow Config::merge to accept a basic array.
  CHANGELOG-4.0.md
  phalcon/config.zep
  phalcon/di.zep
  tests/unit/Config/MergeCest.php
Labels: Enhancement

#13831 renamed phalcon\mvc\url to phalcon\url
  CHANGELOG-4.0.md
  phalcon/di/factorydefault.zep
  phalcon/di/injectable.zep
  phalcon/http/response.zep
  phalcon/tag.zep
  phalcon/url.zep
  phalcon/url/exception.zep
  phalcon/urlinterface.zep
  tests/_config/bootstrap.php
  tests/_data/fixtures/Traits/DiTrait.php
  tests/integration/Mvc/View/Engine/Volt/CompilerCest.php
  tests/integration/Url/GetCest.php
  tests/integration/Url/GetSetBasePathCest.php
  tests/integration/Url/GetSetBaseUriCest.php
  tests/integration/Url/GetSetDICest.php
  tests/integration/Url/GetSetStaticBaseUriCest.php
  tests/integration/Url/GetStaticCest.php
  tests/integration/Url/PathCest.php
  tests/unit/Di/FactoryDefault/ConstructCest.php
Labels: Enhancement

#13826 T13336 find first null
  CHANGELOG-4.0.md
  phalcon/mvc/model.zep
  tests/integration/Mvc/Model/FindFirstCest.php
Labels: Breaks BC, Bug - Low

#13835 Install MySQL 5.7 on Travis CI [skip appveyor]
  .ci/install-mysql-5.7.sh
  .travis.yml
Labels: Testing

#13849 T13844 mcall undefined errors
  ext/config.w32
  ext/phalcon/logger/formatter/syslog.zep.c
  phalcon/logger/formatter/syslog.zep
Labels: Bug - Low

#13839 [#11926] Changed view engine service closures to no longer receive th…
  CHANGELOG-4.0.md
  phalcon/mvc/view.zep
  phalcon/mvc/view/simple.zep
  tests/integration/Mvc/View/Engine/Volt/CompilerCest.php
Labels: New Feature Request

#13840 Changed Volt compiler options.
  phalcon/mvc/view/engine/volt/compiler.zep
Labels: New Feature Request

#13854 Dispatcher handlercache
  phalcon/dispatcher.zep
Labels: Enhancement

#13762 Allow grouped config loader to determine adaptor from file extension.
  CHANGELOG-4.0.md
  phalcon/config/adapter/grouped.zep
  tests/unit/Config/Adapter/Grouped/ConstructCest.php
Labels: Enhancement

#13866 Fixed #13858 - Nanobox config fails for php 7.3
  tests/_ci/nanobox/boxfile.7.3.yml
Labels: Bug - Low
