Repository phalcon/cphalcon, pull requests merged in 2019-12, with the labels that each got.

#14572 Badges
  README.md
Labels: 4.0, Enhancement

#14571 [#14556] - Corrected getQuery to treat 0 as not empty
  CHANGELOG-4.0.md
  phalcon/Collection.zep
  phalcon/Config/Adapter/Json.zep
  phalcon/Debug/Dump.zep
  phalcon/Helper/Json.zep
  phalcon/Http/Request.zep
  phalcon/Http/Response.zep
  phalcon/Logger/Formatter/Json.zep
  tests/unit/Http/Request/GetPostCest.php
  tests/unit/Http/Request/GetQueryCest.php
Labels: 4.0, Bug - Low

#14587 Add two tests to check addInherit
  tests/unit/Acl/Adapter/Memory/AddInheritCest.php
Labels: 4.0, Testing

#14606 Refactor tests
  tests/unit/Helper/Str/DecrementCest.php
  tests/unit/Helper/Str/IncrementCest.php
Labels: 4.0, Testing

#14634 T14633 request fileinterface
  CHANGELOG-4.0.md
  phalcon/Http/Request/FileInterface.zep
Labels: 4.0, Bug - Low

#14638 Double names causing issues in stubs
  phalcon/Config/Adapter/Json.zep
  phalcon/Logger/Formatter/Json.zep
  phalcon/Storage/Serializer/Json.zep
Labels: 4.1, Enhancement

#14645 Fixed Mysql column definition
  phalcon/Db/Dialect/Mysql.zep
  tests/_data/fixtures/Traits/DialectTrait.php
  tests/integration/Db/Dialect/Mysql/GetColumnDefinitionCest.php
Labels: 4.0, Bug - Medium

#14650 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 4.0, enhancement
