Repository phalcon/cphalcon, pull requests merged in 2019-10, with the labels that each got.

#14442 Add Discord shield
  README.md
Labels: 4.0, Hacktoberfest

#14447 Fixed return type on Phalcon\Mvc\View\Engine\AbstractEngine::partial
  CHANGELOG-4.0.md
  phalcon/Mvc/View/Engine/AbstractEngine.zep
  phalcon/Mvc/View/Engine/EngineInterface.zep
Labels: 4.0, Breaks BC, Bug - Medium

#14486 [#14485] ignore_unknown_columns global is respected by update and insert
  CHANGELOG-4.0.md
  phalcon/Mvc/Model.zep
Labels: 4.0, Bug - Low

#14490 Fix return type docblock
  phalcon/Mvc/Model/Criteria.zep
Labels: 4.0, Enhancement
