Repository phalcon/cphalcon, pull requests merged in 2019-05, with the labels that each got.

#14032 Updated CFLAG default build param
  CHANGELOG-3.4.md
  build/install
Labels: Enhancement

#14041 Null checking is now done without 'typeof'.
  phalcon/Cli/Router.zep
  phalcon/Db/Adapter.zep
  phalcon/Db/Adapter/Pdo/Mysql.zep
  phalcon/Db/Adapter/Pdo/Postgresql.zep
  phalcon/Debug.zep
  phalcon/Forms/Element.zep
  phalcon/Forms/Form.zep
  phalcon/Mvc/Model.zep
  phalcon/Mvc/Model/Metadata.zep
  phalcon/Mvc/Model/Query.zep
  phalcon/Mvc/Model/Query/Builder.zep
  phalcon/Mvc/Router.zep
  phalcon/Mvc/Router/Annotations.zep
  phalcon/Mvc/View.zep
  phalcon/Mvc/View/Engine/Volt/Compiler.zep
  phalcon/Paginator/Adapter/QueryBuilder.zep
  phalcon/Tag.zep
  phalcon/Validation.zep
  phalcon/cache/backend.zep
  phalcon/cache/multiple.zep
Labels: Enhancement

#14045 Refactored Volt Compiler ::compile().
  phalcon/Mvc/View/Engine/Volt/Compiler.zep
Labels: Enhancement

#14043 Refactored various methods in Events\Manager
  phalcon/Events/Manager.zep
Labels: Enhancement

#14028 [RFC] Remove model namespace aliases
  CHANGELOG-4.0.md
  phalcon/Mvc/Model/Manager.zep
  phalcon/Mvc/Model/ManagerInterface.zep
  phalcon/Mvc/Model/Query.zep
  tests/integration/Mvc/Model/Manager/GetNamespaceAliasCest.php
  tests/integration/Mvc/Model/Manager/GetNamespaceAliasesCest.php
  tests/integration/Mvc/Model/Manager/RegisterNamespaceAliasCest.php
  tests/integration/Mvc/Model/Refactor-ManagerCest.php
Labels: Breaks BC, Enhancement, Request For Comments

#14077 Loading a Module (either MVC or CLI) now throws an exception properly
  CHANGELOG-4.0.md
  phalcon/Cli/Console.zep
  phalcon/Mvc/Application.zep
  tests/cli/Cli/Console/GetModuleCest.php
  tests/cli/Cli/Console/RegisterModulesCest.php
  tests/integration/Mvc/Application/RegisterModulesCest.php
Labels: Enhancement

#14065 Bind parameters and bind types are now always arrays in Mvc\Model\Query
  CHANGELOG-4.0.md
  phalcon/Mvc/Model/Query.zep
  phalcon/Mvc/Model/Query/Builder.zep
  phalcon/Mvc/Model/QueryInterface.zep
Labels: Breaks BC, Docs needed, Enhancement

#14079 T13869 crypt aes 256 gcm
  CHANGELOG-4.0.md
  phalcon/Crypt.zep
  phalcon/CryptInterface.zep
  tests/unit/Crypt/EncryptBase64Cest.php
  tests/unit/Crypt/EncryptCest.php
  tests/unit/Crypt/SetPaddingCest.php
Labels: Bug - Low

#14086 T10839 many to many relationships
  CHANGELOG-4.0.md
  phalcon/Mvc/Model/Manager.zep
Labels: Bug - Medium

#14106 Libmemcached adapters to use different persistentId by default
  CHANGELOG-4.0.md
  phalcon/Mvc/Model/MetaData/Libmemcached.zep
Labels: Bug - Medium

#14115 Updated Model\Manager relations getter functions
  CHANGELOG-4.0.md
  phalcon/Mvc/Model.zep
  phalcon/Mvc/Model/Manager.zep
  phalcon/Mvc/Model/ManagerInterface.zep
  tests/_data/fixtures/models/AlbumORama/Albums.php
  tests/integration/Mvc/Model/Manager/GetRelationRecordsCest.php
Labels: Breaks BC, Bug - Medium, Docs needed

#13354 Fix segfault on Model::save() with circular relations
  CHANGELOG-4.0.md
  phalcon/Mvc/Model.zep
  tests/integration/Mvc/Model/SaveCest.php
Labels: Bug - Low, Tests needed

#14131 Paginator tests
  tests/integration/Paginator/Adapter/Model/PaginateCest.php
  tests/integration/Paginator/Adapter/QueryBuilder/GetLimitCest.php
  tests/integration/Paginator/Adapter/QueryBuilder/GetQueryBuilderCest.php
  tests/integration/Paginator/Adapter/QueryBuilder/GetSetLimitCest.php
  tests/integration/Paginator/Adapter/QueryBuilder/GetSetQueryBuilderCest.php
  tests/integration/Paginator/Adapter/QueryBuilder/PaginateCest.php
  tests/integration/Paginator/Adapter/QueryBuilder/Refactor-PaginatorQueryBuilderCest.php
  tests/integration/Paginator/Adapter/QueryBuilder/SetLimitCest.php
  tests/integration/Paginator/Adapter/QueryBuilder/SetQueryBuilderCest.php
  tests/integration/Refactor-PaginatorCest.php
Labels: Testing

#14135 Reenabled Flash Session tests.
  tests/unit/Flash/SessionCest.php
Labels: Testing
