Repository phalcon/cphalcon, pull requests merged in 2019-01, with the labels that each got.

#13741 Fixed Phalcon\Acl docblock
  phalcon/acl.zep
Labels: Enhancement

#13746 Fixed session adapters to properly implement SessionHandlerInterface::write
  CHANGELOG-4.0.md
  phalcon/session/adapter/files.zep
  phalcon/session/adapter/libmemcached.zep
  phalcon/session/adapter/noop.zep
  phalcon/session/adapter/redis.zep
Labels: Bug - Medium

#13753 Drop PHP 5 support from Volt
  ext/phalcon/mvc/view/engine/volt/generate
  ext/phalcon/mvc/view/engine/volt/parser.c
  ext/phalcon/mvc/view/engine/volt/parser.php5.c
  ext/phalcon/mvc/view/engine/volt/parser.php5.h
  ext/phalcon/mvc/view/engine/volt/parser.php5.inc.h
  ext/phalcon/mvc/view/engine/volt/parser.php5.lemon
  ext/phalcon/mvc/view/engine/volt/scanner.c
Labels: Enhancement

#13754 Cleaned up and refactor Volt tests
  .ci/run-volt-tests.sh
  .travis.yml
  tests/_ci/volt-tests.sh
  tests/syntax/.gitignore
  tests/syntax/tests/volt/statements/switchcase/001.diff
  tests/syntax/tests/volt/statements/switchcase/001.exp
  tests/syntax/tests/volt/statements/switchcase/001.php
  tests/syntax/tests/volt/statements/switchcase/001.sh
  tests/syntax/tests/volt/statements/switchcase/002.diff
  tests/syntax/tests/volt/statements/switchcase/002.php
  tests/syntax/tests/volt/statements/switchcase/002.sh
  tests/syntax/tests/volt/statements/switchcase/003.diff
  tests/syntax/tests/volt/statements/switchcase/003.php
  tests/syntax/tests/volt/statements/switchcase/003.phpt
  tests/syntax/tests/volt/statements/switchcase/003.sh
  tests/syntax/tests/volt/statements/switchcase/004.diff
  tests/syntax/tests/volt/statements/switchcase/004.exp
  tests/syntax/tests/volt/statements/switchcase/004.php
  tests/syntax/tests/volt/statements/switchcase/004.phpt
  tests/syntax/tests/volt/statements/switchcase/004.sh
  tests/syntax/tests/volt/statements/switchcase/005.diff
  tests/syntax/tests/volt/statements/switchcase/005.exp
  tests/syntax/tests/volt/statements/switchcase/005.php
  tests/syntax/tests/volt/statements/switchcase/005.phpt
  tests/syntax/tests/volt/statements/switchcase/005.sh
  tests/syntax/tests/volt/statements/switchcase/006.diff
  tests/syntax/tests/volt/statements/switchcase/006.exp
  tests/syntax/tests/volt/statements/switchcase/006.php
  tests/syntax/tests/volt/statements/switchcase/006.phpt
  tests/syntax/tests/volt/statements/switchcase/006.sh
  tests/syntax/tests/volt/statements/switchcase/007.diff
  tests/syntax/tests/volt/statements/switchcase/007.exp
  tests/syntax/tests/volt/statements/switchcase/007.php
  tests/syntax/tests/volt/statements/switchcase/007.phpt
  tests/syntax/tests/volt/statements/switchcase/007.sh
  tests/syntax/tests/volt/statements/switchcase/008.diff
  tests/syntax/tests/volt/statements/switchcase/008.exp
  tests/syntax/tests/volt/statements/switchcase/008.php
  tests/syntax/tests/volt/statements/switchcase/008.sh
  tests/syntax/tests/volt/statements/switchcase/009.diff
  tests/syntax/tests/volt/statements/switchcase/009.exp
  tests/syntax/tests/volt/statements/switchcase/009.php
  tests/syntax/tests/volt/statements/switchcase/009.phpt
  tests/syntax/tests/volt/statements/switchcase/009.sh
  tests/syntax/tests/volt/statements/switchcase/010.diff
  tests/syntax/tests/volt/statements/switchcase/010.exp
  tests/syntax/tests/volt/statements/switchcase/010.php
  tests/syntax/tests/volt/statements/switchcase/010.phpt
  tests/syntax/tests/volt/statements/switchcase/010.sh
  tests/syntax/volt/statements/switchcase/001.phpt
  tests/syntax/volt/statements/switchcase/002.phpt
  tests/syntax/volt/statements/switchcase/003.phpt
  tests/syntax/volt/statements/switchcase/004.phpt
  tests/syntax/volt/statements/switchcase/005.phpt
  tests/syntax/volt/statements/switchcase/006.phpt
  tests/syntax/volt/statements/switchcase/007.phpt
  tests/syntax/volt/statements/switchcase/008.phpt
  tests/syntax/volt/statements/switchcase/009.phpt
  tests/syntax/volt/statements/switchcase/010.phpt
Labels: Testing

#13748 T13007 nativearray missing patch
  .travis.yml
  phalcon/translate/adapter/nativearray.zep
  tests/unit/Translate/Adapter/NativeArray/NotFoundCest.php
Labels: Enhancement

#13695 Fixes #13459: Removed tags that accept multiple args from array helper
  CHANGELOG-4.0.md
  phalcon/mvc/view/engine/volt/compiler.zep
  tests/unit/Mvc/View/Engine/Volt/Compiler/CompileStringCest.php
Labels: Bug - Low

#13767 Build Phalcon for PHP 7.3 on AppVeyor
  .ci/appveyor.psm1
  .travis.yml
  appveyor.yml
  build/.gitignore
  tests/_ci/appveyor.psm1
Labels: Feature

#13770 T13769 acl no arguments default action deny
  phalcon/acl/adapter.zep
  phalcon/acl/adapter/memory.zep
  phalcon/acl/adapterinterface.zep
  phalcon/acl/operation.zep
  phalcon/acl/subject.zep
  tests/unit/Acl/Adapter/Memory/GetNoArgumentsDefaultActionCest.php
  tests/unit/Acl/Adapter/Memory/GetSetNoArgumentsDefaultActionCest.php
  tests/unit/Acl/Adapter/Memory/SetNoArgumentsDefaultActionCest.php
  tests/unit/Session/ManagerCest.php
  tests/unit/Translate/Adapter/NativeArray/NotFoundCest.php
Labels: Breaks BC, Bug - Medium

#13772 T13771 service locator
  phalcon/html/helper/abstracthelper.zep
  phalcon/html/helper/anchor.zep
  phalcon/html/helper/button.zep
  phalcon/html/helper/element.zep
  phalcon/html/helper/form.zep
  phalcon/html/helper/formclose.zep
  phalcon/html/helper/textarea.zep
  phalcon/html/tag.zep
  phalcon/html/taglocator.zep
  phalcon/html/taglocatorfactory.zep
  phalcon/service/exception.zep
  phalcon/service/locator.zep
  phalcon/service/locatorfactoryinterface.zep
  phalcon/service/locatorinterface.zep
  tests/_data/fixtures/Service/HelloService.php
  tests/_data/fixtures/Traits/DiTrait.php
  tests/unit/Html/Helper/AnchorCest.php
  tests/unit/Html/Helper/ButtonCest.php
  tests/unit/Html/Helper/ElementCest.php
  tests/unit/Html/Helper/FormCest.php
  tests/unit/Html/Helper/FormCloseCest.php
  tests/unit/Html/Helper/TextAreaCest.php
  tests/unit/Html/TagLocator/ConstructCest.php
  tests/unit/Html/TagLocator/GetSetHasCest.php
  tests/unit/Html/TagLocator/UnderscoreCallCest.php
  tests/unit/Html/TagLocatorFactory/NewInstanceCest.php
  tests/unit/Service/Locator/ConstructCest.php
  tests/unit/Service/Locator/GetSetHasCest.php
  tests/unit/Service/Locator/UnderscoreCallCest.php
Labels: Feature

#13774 #13717: Cleaned up the `Phalcon\Mvc\Model\Metadata\Redis` constructor
  phalcon/mvc/model/metadata/redis.zep
Labels: Enhancement

#13775 Removed Phalcon\Mvc\User
  CHANGELOG-4.0.md
  phalcon/mvc/user/component.zep
  phalcon/mvc/user/plugin.zep
  phalcon/plugin.zep
Labels: Enhancement
