Repository phalcon/cphalcon, pull requests merged in 2019-04, with the labels that each got.

#13930 Refactored SoftDelete model behaviour.
  CHANGELOG-4.0.md
  phalcon/Mvc/Collection/Behavior/SoftDelete.zep
  phalcon/Mvc/Model/Behavior/SoftDelete.zep
Labels: Bug - Low

#13933 CLI Routes with bad classnames now throw an exception
  CHANGELOG-4.0.md
  phalcon/Cli/Router/Route.zep
  tests/cli/Cli/RouterCest.php
Labels: Breaks BC, Enhancement

#13935 Dispatcher::forward() and Dispatcher::setParams() now require an array as a parameter
  CHANGELOG-4.0.md
  phalcon/Dispatcher.zep
  phalcon/DispatcherInterface.zep
Labels: Breaks BC, Enhancement

#13939 Phalcon\Translate\InterpolatorInterface now only accepts placeholder arrays
  CHANGELOG-4.0.md
  phalcon/Translate/Interpolator/AssociativeArray.zep
  phalcon/Translate/Interpolator/IndexedArray.zep
  phalcon/Translate/InterpolatorInterface.zep
Labels: Breaks BC, Enhancement

#13925 Removed pointless property and variables from Volt compiler
  CHANGELOG-4.0.md
  phalcon/Mvc/View/Engine/Volt/Compiler.zep
Labels: Enhancement

#13936 [NFR] - added description property to Cli\Router\Route
  CHANGELOG-4.0.md
  phalcon/Cli/Router/Route.zep
  phalcon/Cli/Router/RouteInterface.zep
  tests/cli/Cli/Router/Route/GetDescriptionCest.php
  tests/cli/Cli/Router/Route/SetDescriptionCest.php
Labels: Feature - NFR

#13928 Refactored Html\TagLocatorFactory::getEscaper() method.
  phalcon/Html/TagLocatorFactory.zep
Labels: Enhancement

#13945 Removed assigning properties via save() in models (as per #12317)
  CHANGELOG-4.0.md
  phalcon/Mvc/Model.zep
  phalcon/Mvc/Model/Resultset.zep
Labels: Breaks BC, Enhancement

#13958 T13954 enhance helpers 6
  CHANGELOG-4.0.md
  phalcon/Helper/Arr.zep
  phalcon/Helper/Str.zep
  phalcon/Text.zep
  tests/unit/Helper/Arr/ChunkCest.php
  tests/unit/Helper/Arr/FirstCest.php
  tests/unit/Helper/Arr/FirstKeyCest.php
  tests/unit/Helper/Arr/FlattenCest.php
  tests/unit/Helper/Arr/GroupCest.php
  tests/unit/Helper/Arr/IsUniqueCest.php
  tests/unit/Helper/Arr/LastCest.php
  tests/unit/Helper/Arr/LastKeyCest.php
  tests/unit/Helper/Arr/OrderCest.php
  tests/unit/Helper/Arr/PluckCest.php
  tests/unit/Helper/Arr/SliceLeftCest.php
  tests/unit/Helper/Arr/SliceRightCest.php
  tests/unit/Helper/Arr/SplitCest.php
  tests/unit/Helper/Arr/ValidateAllCest.php
  tests/unit/Helper/Arr/ValidateAnyCest.php
  tests/unit/Helper/Str/CamelizeCest.php
  tests/unit/Helper/Str/ConcatCest.php
  tests/unit/Helper/Str/CountVowelsCest.php
  tests/unit/Helper/Str/DecapitalizeCest.php
  tests/unit/Helper/Str/DynamicCest.php
  tests/unit/Helper/Str/EndsWithCest.php
  tests/unit/Helper/Str/FirstBetweenCest.php
  tests/unit/Helper/Str/HumanizeCest.php
  tests/unit/Helper/Str/IncludesCest.php
  tests/unit/Helper/Str/IncrementCest.php
  tests/unit/Helper/Str/IsAnagramCest.php
  tests/unit/Helper/Str/IsLowerCest.php
  tests/unit/Helper/Str/IsPalindromeCest.php
  tests/unit/Helper/Str/IsUpperCest.php
  tests/unit/Helper/Str/LowerCest.php
  tests/unit/Helper/Str/RandomCest.php
  tests/unit/Helper/Str/ReduceSlashesCest.php
  tests/unit/Helper/Str/StartsWithCest.php
  tests/unit/Helper/Str/UncamelizeCest.php
  tests/unit/Helper/Str/UnderscoreCest.php
  tests/unit/Helper/Str/UpperCest.php
Labels: Enhancement

#13950 Model methods that extend Model Manager functionality are now final
  CHANGELOG-4.0.md
  phalcon/Mvc/Model.zep
  tests/_data/fixtures/models/Abonnes.php
  tests/_data/fixtures/models/Boutique/Robotters.php
  tests/_data/fixtures/models/Deles.php
  tests/_data/fixtures/models/GossipRobots.php
  tests/_data/fixtures/models/Language.php
  tests/_data/fixtures/models/LanguageI18n.php
  tests/_data/fixtures/models/ModelWithStringField.php
  tests/_data/fixtures/models/News/Subscribers.php
  tests/_data/fixtures/models/People.php
  tests/_data/fixtures/models/Personers.php
  tests/_data/fixtures/models/Pessoas.php
  tests/_data/fixtures/models/Relations/Deles.php
  tests/_data/fixtures/models/Relations/M2MParts.php
  tests/_data/fixtures/models/Relations/M2MRobots.php
  tests/_data/fixtures/models/Relations/M2MRobotsParts.php
  tests/_data/fixtures/models/Relations/RelationsParts.php
  tests/_data/fixtures/models/Relations/RelationsRobots.php
  tests/_data/fixtures/models/Relations/RelationsRobotsParts.php
  tests/_data/fixtures/models/Relations/Robotters.php
  tests/_data/fixtures/models/Relations/RobottersDeles.php
  tests/_data/fixtures/models/Relations/Some/Deles.php
  tests/_data/fixtures/models/Relations/Some/Parts.php
  tests/_data/fixtures/models/Relations/Some/Products.php
  tests/_data/fixtures/models/Relations/Some/Robots.php
  tests/_data/fixtures/models/Relations/Some/RobotsParts.php
  tests/_data/fixtures/models/Relations/Some/Robotters.php
  tests/_data/fixtures/models/Relations/Some/RobottersDeles.php
  tests/_data/fixtures/models/Robos.php
  tests/_data/fixtures/models/Robots2.php
  tests/_data/fixtures/models/RobotsExtended.php
  tests/_data/fixtures/models/Robotters.php
  tests/_data/fixtures/models/RobottersDeles.php
  tests/_data/fixtures/models/Robotto.php
  tests/_data/fixtures/models/Select.php
  tests/_data/fixtures/models/Snapshot/Robotters.php
  tests/_data/fixtures/models/Snapshot/Subscribers.php
  tests/_data/fixtures/models/Some/Deles.php
  tests/_data/fixtures/models/Some/Parts.php
  tests/_data/fixtures/models/Some/Products.php
  tests/_data/fixtures/models/Some/Robots.php
  tests/_data/fixtures/models/Some/RobotsParts.php
  tests/_data/fixtures/models/Some/Robotters.php
  tests/_data/fixtures/models/Some/RobottersDeles.php
  tests/_data/fixtures/models/Statistics/AgeStats.php
  tests/_data/fixtures/models/Statistics/CityStats.php
  tests/_data/fixtures/models/Statistics/CountryStats.php
  tests/_data/fixtures/models/Statistics/GenderStats.php
  tests/_data/fixtures/models/Subscribers.php
  tests/integration/Mvc/Model/Refactor-ManagerCest.php
Labels: Breaks BC

#13952 CS on Mvc\Model
  phalcon/Mvc/Model.zep
  phalcon/Mvc/Model/Behavior.zep
  phalcon/Mvc/Model/Behavior/Timestampable.zep
  phalcon/Mvc/Model/Binder.zep
  phalcon/Mvc/Model/Criteria.zep
  phalcon/Mvc/Model/CriteriaInterface.zep
  phalcon/Mvc/Model/Manager.zep
  phalcon/Mvc/Model/ManagerInterface.zep
  phalcon/Mvc/Model/Metadata.zep
  phalcon/Mvc/Model/Metadata/Apcu.zep
  phalcon/Mvc/Model/Metadata/Files.zep
  phalcon/Mvc/Model/Metadata/Libmemcached.zep
  phalcon/Mvc/Model/Metadata/Memory.zep
  phalcon/Mvc/Model/Metadata/Redis.zep
  phalcon/Mvc/Model/Metadata/Session.zep
  phalcon/Mvc/Model/Query.zep
  phalcon/Mvc/Model/Query/Builder.zep
  phalcon/Mvc/Model/Query/Status.zep
  phalcon/Mvc/Model/QueryInterface.zep
  phalcon/Mvc/Model/Relation.zep
  phalcon/Mvc/Model/Resultset.zep
  phalcon/Mvc/Model/Resultset/Complex.zep
  phalcon/Mvc/Model/Resultset/Simple.zep
  phalcon/Mvc/Model/ResultsetInterface.zep
  phalcon/Mvc/Model/Transaction.zep
  phalcon/Mvc/Model/Transaction/Failed.zep
  phalcon/Mvc/Model/Transaction/Manager.zep
  phalcon/Mvc/Model/Transaction/ManagerInterface.zep
  phalcon/Mvc/Model/TransactionInterface.zep
  phalcon/Mvc/Model/ValidationFailed.zep
Labels: Breaks BC

#13960 Added Image\Adapter\Gd::getVersion().
  CHANGELOG-4.0.md
  phalcon/Image/Adapter.zep
  phalcon/Image/Adapter/Gd.zep
Labels: Feature - NFR

#13969 `Phalcon\Acl\Adapter\Memory::dropComponentAccess()` now properly unsets values
  CHANGELOG-4.0.md
  phalcon/Acl/Adapter/Memory.zep
Labels: Bug - Medium

#13955 Tidied up Validation
  phalcon/Validation.zep
  phalcon/Validation/Validator.zep
  phalcon/Validation/Validator/Alnum.zep
  phalcon/Validation/Validator/Alpha.zep
  phalcon/Validation/Validator/Callback.zep
  phalcon/Validation/Validator/Confirmation.zep
  phalcon/Validation/Validator/CreditCard.zep
  phalcon/Validation/Validator/Date.zep
  phalcon/Validation/Validator/Digit.zep
  phalcon/Validation/Validator/Email.zep
  phalcon/Validation/Validator/File.zep
  phalcon/Validation/Validator/Identical.zep
  phalcon/Validation/Validator/Ip.zep
  phalcon/Validation/Validator/Numericality.zep
  phalcon/Validation/Validator/PresenceOf.zep
  phalcon/Validation/Validator/Regex.zep
  phalcon/Validation/Validator/Uniqueness.zep
  phalcon/Validation/Validator/Url.zep
  phalcon/ValidationInterface.zep
Labels: Enhancement

#13962 Query Builder's GROUP BY field is now always an array
  CHANGELOG-4.0.md
  phalcon/Mvc/Model/Query/Builder.zep
  phalcon/Mvc/Model/Query/BuilderInterface.zep
Labels: Breaks BC, Docs needed, Feature - NFR

#13971 Corrected Volt option variables (fixes #13968)
  CHANGELOG-4.0.md
  phalcon/Mvc/View/Engine/Volt/Compiler.zep
Labels: Bug - Medium, Docs needed

#13976 Tidied up Criteria.
  phalcon/Mvc/Model/Criteria.zep
  phalcon/Mvc/Model/CriteriaInterface.zep
Labels: Enhancement

#13932 Cli\Route::delimiterPath now has a default value
  CHANGELOG-4.0.md
  phalcon/Cli/Router/Route.zep
Labels: Enhancement

#13977 Criteria::limit() now takes 'offset' as an integer.
  CHANGELOG-4.0.md
  phalcon/Mvc/Model/Criteria.zep
  phalcon/Mvc/Model/CriteriaInterface.zep
Labels: Breaks BC, Enhancement

#13988 Simple View stuff
  CHANGELOG-4.0.md
  phalcon/Mvc/View/Simple.zep
Labels: Breaks BC, Enhancement

#13987 Allowing ModelsManager get/setModelSource to be overrideable
  CHANGELOG-4.0.md
  phalcon/Mvc/Model/Manager.zep
Labels: Enhancement

#13985 Fixed saving a model after fetching its related records
  CHANGELOG-4.0.md
  phalcon/Mvc/Model.zep
  tests/integration/Mvc/Model/Refactor-ModelsRelationsMagicCest.php
Labels: Bug - Low

#14001 Added addConnect(), addPurge() and addTrace() to Router Group
  CHANGELOG-4.0.md
  phalcon/Annotations/Reflection.zep
  phalcon/Mvc/Router/Group.zep
  phalcon/Mvc/Router/GroupInterface.zep
  tests/integration/Mvc/Router/Group/AddDeleteCest.php
  tests/integration/Mvc/Router/Group/AddGetCest.php
  tests/integration/Mvc/Router/Group/AddHeadCest.php
  tests/integration/Mvc/Router/Group/AddOptionsCest.php
  tests/integration/Mvc/Router/Group/AddPatchCest.php
  tests/integration/Mvc/Router/Group/AddPostCest.php
  tests/integration/Mvc/Router/Group/AddPutCest.php
  tests/integration/Mvc/Router/Group/GetPrefixCest.php
Labels: Breaks BC, Enhancement

#13989 The property 'options' is always an array in Model Relations.
  CHANGELOG-4.0.md
  phalcon/Mvc/Model/Relation.zep
  phalcon/Mvc/Model/RelationInterface.zep
  tests/integration/Mvc/Model/Relation/GetFieldsCest.php
  tests/integration/Mvc/Model/Relation/GetOptionCest.php
  tests/integration/Mvc/Model/Relation/GetOptionsCest.php
  tests/integration/Mvc/Model/Relation/GetParamsCest.php
  tests/integration/Mvc/Model/Relation/GetReferencedModelCest.php
  tests/integration/Mvc/Model/Relation/GetTypeCest.php
Labels: Breaks BC, Enhancement

#14012 Logger\Adapter\AbstractAdapter::process() is now actually abstract.
  CHANGELOG-4.0.md
  phalcon/Logger/Adapter/AbstractAdapter.zep
Labels: Enhancement

#14015 [WIP] Added variable types.
  phalcon/Acl/Adapter/Memory.zep
  phalcon/Annotations/Adapter.zep
  phalcon/Annotations/Adapter/Files.zep
  phalcon/Annotations/Annotation.zep
  phalcon/Annotations/Collection.zep
  phalcon/Annotations/Reader.zep
  phalcon/Assets/Asset.zep
  phalcon/Cli/Console.zep
  phalcon/Cli/Dispatcher.zep
  phalcon/Cli/Router.zep
  phalcon/Cli/Router/Route.zep
  phalcon/Config/Adapter/Grouped.zep
  phalcon/Config/Adapter/Ini.zep
  phalcon/Config/Factory.zep
  phalcon/Db/Adapter/Pdo/Mysql.zep
  phalcon/Db/Dialect.zep
  phalcon/Debug/Dump.zep
  phalcon/Events/Manager.zep
  phalcon/Factory.zep
  phalcon/Forms/Form.zep
  phalcon/Helper/Arr.zep
  phalcon/Helper/Str.zep
  phalcon/Html/Helper/AbstractHelper.zep
  phalcon/Logger/Adapter/Syslog.zep
  phalcon/Logger/Formatter/AbstractFormatter.zep
  phalcon/Messages/Messages.zep
  phalcon/Mvc/Micro.zep
  phalcon/Mvc/Model.zep
  phalcon/Mvc/Model/Behavior.zep
  phalcon/Mvc/Model/Criteria.zep
  phalcon/Mvc/Model/Manager.zep
  phalcon/Mvc/Model/Metadata.zep
  phalcon/Mvc/Model/Metadata/Files.zep
  phalcon/Mvc/Model/Metadata/Strategy/Annotations.zep
  phalcon/Mvc/Model/Metadata/Strategy/Introspection.zep
  phalcon/Mvc/Model/Query.zep
  phalcon/Mvc/Model/Resultset/Complex.zep
  phalcon/Mvc/Model/Resultset/Simple.zep
  phalcon/Mvc/Router/Route.zep
  phalcon/Mvc/View/Engine/Volt.zep
  phalcon/Mvc/View/Engine/Volt/Compiler.zep
  phalcon/Paginator/Adapter/QueryBuilder.zep
  phalcon/Version.zep
Labels: Enhancement

#14026 Fixed Phalcon\Config\Adapter\Ini() to handle arrays correctly
  CHANGELOG-4.0.md
  phalcon/Config/Adapter/Ini.zep
  tests/_data/assets/config/config-with-constants.ini
  tests/unit/Config/Adapter/Ini/ConstructCest.php
Labels: Bug - Medium, Docs needed
