Repository phalcon/cphalcon, pull requests merged in 2020-09, with the labels that each got.

#15150 T15129 - Cookies::set() options parameter fixed
  CHANGELOG-4.1.md
  phalcon/Http/Response/Cookies.zep
  tests/unit/Http/Response/Cookies/GetSetCest.php
Labels: 4.1.0, bug

#15152 #15142 - Fix cookies options
  CHANGELOG-4.1.md
  phalcon/Http/Cookie.zep
Labels: 4.1.0, bug

#15153 #15077 - Update missed fix in CHANGELOG-4.1.md
  CHANGELOG-4.1.md
Labels: 4.1.0

#15158 Feature: callable relation params
  CHANGELOG-4.1.md
  phalcon/Mvc/Model/Relation.zep
  tests/_data/fixtures/models/Customers.php
  tests/database/Mvc/Model/DeleteCest.php
Labels: 4.1.0, new feature request

#15160 T15118 - Crypt perfomance issues
  CHANGELOG-4.1.md
  phalcon/Crypt.zep
Labels: 4.1.0, bug
