Repository phalcon/cphalcon, pull requests merged in 2020-05, with the labels that each got.

#14969 Bump version to 4.0.6
  phalcon/Version.zep
Labels: 4.0.6

#14974 Review MySQL default null and nullable column definition
  CHANGELOG-4.0.md
  phalcon/Db/Dialect/Mysql.zep
  tests/integration/Db/Dialect/Mysql/AddColumnCest.php
  tests/integration/Db/Dialect/Mysql/CreateTableCest.php
  tests/integration/Db/Dialect/Mysql/ModifyColumnCest.php
Labels: 4.0.6, bug

#14981 Fixed Assets tests
  tests/unit/Assets/Asset/Css/GetRealSourcePathCest.php
  tests/unit/Assets/Asset/GetRealSourcePathCest.php
  tests/unit/Assets/Asset/Js/GetRealSourcePathCest.php
Labels: 4.0.6

#14984 Fixed incorrect return type hint for setSignKey
  CHANGELOG-4.0.md
  phalcon/Http/Response/Cookies.zep
  tests/unit/Http/Response/Cookies/DeleteCest.php
  tests/unit/Http/Response/Cookies/SetSignKeyCest.php
Labels: 4.0.6

#14985 Improved content type check for Response::__construct
  CHANGELOG-4.0.md
  phalcon/Http/Response.zep
  tests/unit/Http/Response/ConstructCest.php
  tests/unit/Http/Response/GetSetContentCest.php
Labels: 4.0.6

#14986 Fixed incorrect return type hints for ConfigFactory
  CHANGELOG-4.0.md
  phalcon/Config/ConfigFactory.zep
  tests/_data/fixtures/Traits/FactoryTrait.php
  tests/unit/Config/ConfigFactory/LoadCest.php
  tests/unit/Config/ConfigFactory/NewInstanceCest.php
Labels: 4.0.6

#14988 Do not use `object` return type hint
  CHANGELOG-4.0.md
  phalcon/Dispatcher/AbstractDispatcher.zep
  phalcon/Dispatcher/DispatcherInterface.zep
  phalcon/Filter.zep
  phalcon/Http/Message/AbstractCommon.zep
  phalcon/Http/Message/AbstractMessage.zep
  phalcon/Http/Message/AbstractRequest.zep
  phalcon/Mvc/Model/Binder.zep
  phalcon/Validation.zep
  phalcon/Validation/ValidationInterface.zep
Labels: 4.0.6

#14991 Fixed default value of Crypt::$key
  CHANGELOG-4.0.md
  phalcon/Crypt.zep
  tests/unit/Crypt/GetSetKeyCest.php
Labels: 4.0.6

#14993 Fixed return type hint for Di::getInternalEventsManager
  CHANGELOG-4.0.md
  phalcon/Di.zep
  tests/unit/Di/GetInternalEventsManagerCest.php
  tests/unit/Di/GetServicesCest.php
  tests/unit/Di/SetInternalEventsManagerCest.php
Labels: 4.0.6

#14995 Changed return type hints for FlashInterface methods
  CHANGELOG-4.0.md
  phalcon/Flash/AbstractFlash.zep
  phalcon/Flash/Direct.zep
  phalcon/Flash/Exception.zep
  phalcon/Flash/FlashInterface.zep
  phalcon/Flash/Session.zep
  tests/unit/Filter/Filter/CustomCest.php
  tests/unit/Filter/Filter/GetSetHasCest.php
  tests/unit/Filter/FilterFactory/NewInstanceCest.php
  tests/unit/Flash/Direct/FlashDirectCustomCSSCest.php
  tests/unit/Flash/Direct/FlashDirectEmptyCSSCest.php
  tests/unit/Flash/Direct/Helper/FlashBase.php
  tests/unit/Flash/DirectCest.php
  tests/unit/Flash/SessionCest.php
Labels: 4.0.6

#14997 Fixed return type hint for InterpolatorFactory::newInstance
  CHANGELOG-4.0.md
  phalcon/Translate/InterpolatorFactory.zep
  tests/unit/Translate/InterpolatorFactory/NewInstanceCest.php
Labels: 4.0.6

#14998 Fixed Phalcon\Test\Database\Mvc\Model\QueryCest
  composer.json
  tests/_data/fixtures/Migrations/AbstractMigration.php
  tests/_data/fixtures/Migrations/CustomersMigration.php
  tests/_data/fixtures/Traits/DiTrait.php
  tests/_data/fixtures/models/CustomersKeepSnapshots.php
  tests/database/Mvc/Model/QueryCest.php
Labels: 4.0.6, testing

#15001 Fixed return type hint for Phalcon\Mvc\Model::sum
  CHANGELOG-4.0.md
  ext/phalcon/mvc/model.zep.c
  ext/phalcon/mvc/model.zep.h
  ext/phalcon/mvc/modelinterface.zep.c
  ext/phalcon/mvc/modelinterface.zep.h
  phalcon/Mvc/Model.zep
  phalcon/Mvc/ModelInterface.zep
  tests/_data/fixtures/Traits/RecordsTrait.php
  tests/database/Mvc/Model/QueryCest.php
  tests/database/Mvc/Model/SumCest.php
Labels: 4.0.6

#15003 Correct database tests
  CHANGELOG-4.0.md
  tests/README.md
  tests/database/Db/Adapter/Pdo/DescribeColumnsCest.php
  tests/database/Mvc/Model/Criteria/FromInputCest.php
Labels: 4.0.6, testing

#15005 Fixed return type for CriteriaInterface::getLimit
  CHANGELOG-4.0.md
  ext/phalcon/mvc/model/criteria.zep.c
  ext/phalcon/mvc/model/criteria.zep.h
  ext/phalcon/mvc/model/criteriainterface.zep.c
  ext/phalcon/mvc/model/criteriainterface.zep.h
  phalcon/Mvc/Model/Criteria.zep
  phalcon/Mvc/Model/CriteriaInterface.zep
  tests/database/Mvc/Model/Criteria/LimitCest.php
Labels: 4.0.6, bug, status: low

#15007 Fixed return type hint for ModelInterface::count
  CHANGELOG-4.0.md
  ext/phalcon/mvc/model.zep.c
  ext/phalcon/mvc/model.zep.h
  ext/phalcon/mvc/modelinterface.zep.c
  ext/phalcon/mvc/modelinterface.zep.h
  phalcon/Mvc/Model.zep
  phalcon/Mvc/ModelInterface.zep
  tests/database/Mvc/Model/CountCest.php
Labels: 4.0.6, bug, status: low

#15009 Changed return type hint for Model::getEventsManager
  CHANGELOG-4.0.md
  ext/phalcon/mvc/model.zep.h
  ext/phalcon/mvc/model/manager.zep.c
  ext/phalcon/mvc/model/manager.zep.h
  phalcon/Mvc/Model.zep
  phalcon/Mvc/Model/Manager.zep
  tests/_data/fixtures/models/Invoices.php
  tests/database/Db/Adapter/Pdo/DescribeColumnsCest.php
  tests/database/Mvc/Model/CountCest.php
  tests/database/Mvc/Model/GetSetEventsManagerCest.php
  tests/database/Mvc/Model/QueryCest.php
  tests/database/Mvc/Model/SumCest.php
Labels: 4.0.6, bug, status: low

#15012 Changed MetaData::getDI to throw exception
  CHANGELOG-4.0.md
  ext/phalcon/mvc/model.zep.c
  ext/phalcon/mvc/model/manager.zep.c
  ext/phalcon/mvc/model/metadata.zep.c
  phalcon/Mvc/Model/MetaData.zep
  tests/database/Mvc/Model/MetaData/GetSetDICest.php
Labels: 4.0.6, bug, status: low

#15014 Fixed return type hint for ModelInterface::average
  CHANGELOG-4.0.md
  ext/phalcon/mvc/model.zep.c
  ext/phalcon/mvc/model.zep.h
  ext/phalcon/mvc/modelinterface.zep.c
  ext/phalcon/mvc/modelinterface.zep.h
  phalcon/Mvc/Model.zep
  phalcon/Mvc/ModelInterface.zep
  tests/database/Mvc/Model/AverageCest.php
Labels: 4.0.6, bug, status: low

#15016 Fixed return type hint for MetaData
  CHANGELOG-4.0.md
  ext/phalcon/mvc/model/metadata.zep.c
  ext/phalcon/mvc/model/metadata.zep.h
  ext/phalcon/mvc/model/metadatainterface.zep.h
  phalcon/Mvc/Model/MetaData.zep
  phalcon/Mvc/Model/MetaDataInterface.zep
  tests/database/Mvc/Model/MetaData/GetColumnMapCest.php
Labels: 4.0.6, bug, status: low

#15018 Fixed return type for CriteriaInterface::getColumns
  CHANGELOG-4.0.md
  ext/phalcon/mvc/model/criteria.zep.c
  ext/phalcon/mvc/model/criteria.zep.h
  ext/phalcon/mvc/model/criteriainterface.zep.h
  phalcon/Mvc/Model/Criteria.zep
  phalcon/Mvc/Model/CriteriaInterface.zep
  tests/README.md
  tests/_ci/.env.default
  tests/_ci/.env.travis
  tests/_ci/nanobox/.env.example
  tests/database/Mvc/Model/Criteria/GetColumnsCest.php
Labels: 4.0.6, bug, status: low

#15020 Fixed return type hint for Column::getSize
  CHANGELOG-4.0.md
  ext/phalcon/db/column.zep.c
  ext/phalcon/db/column.zep.h
  ext/phalcon/db/columninterface.zep.c
  ext/phalcon/db/columninterface.zep.h
  phalcon/Db/Column.zep
  phalcon/Db/ColumnInterface.zep
  tests/_data/fixtures/Traits/DbTrait.php
  tests/database/Db/Column/GetSizeCest.php
Labels: 4.0.6, bug, status: low

#15022 Fixed return type hint for Column::getAfterPosition
  CHANGELOG-4.0.md
  ext/phalcon/db/column.zep.c
  ext/phalcon/db/column.zep.h
  ext/phalcon/db/columninterface.zep.h
  phalcon/Db/Column.zep
  phalcon/Db/ColumnInterface.zep
  tests/database/Db/Column/GetAfterPositionCest.php
Labels: 4.0.6, bug, status: low

#14964 Allow any chars from the Extended ASCII table for escaped IDs
  CHANGELOG-4.1.md
  ext/phalcon/mvc/model/query/parser.php7.lemon
  ext/phalcon/mvc/model/query/scanner.c
  ext/phalcon/mvc/model/query/scanner.h
  ext/phalcon/mvc/model/query/scanner.re
  tests/_data/fixtures/Migrations/CustomersMigration.php
  tests/_data/fixtures/Migrations/InvoicesMigration.php
  tests/database/Mvc/Model/QueryCest.php
  tests/run-syntax-tests.sh
  tests/syntax/phql/003.phpt
  tests/syntax/phql/bug14253.phpt
  tests/syntax/phql/bug14535.phpt
Labels: 4.1.0, bug, status: low

#15025 T14936 json decode
  CHANGELOG-4.0.md
  phalcon/Http/Request.zep
  tests/_ci/generate-api-docs.php
Labels: 4.0.6, bug

#15026 Fixed return type hint for Manager::executeQuery
  CHANGELOG-4.0.md
  ext/phalcon/mvc/model/manager.zep.c
  ext/phalcon/mvc/model/manager.zep.h
  ext/phalcon/mvc/model/managerinterface.zep.c
  ext/phalcon/mvc/model/managerinterface.zep.h
  phalcon/Mvc/Model/Manager.zep
  phalcon/Mvc/Model/ManagerInterface.zep
  tests/database/Mvc/Model/Manager/ExecuteQueryCest.php
Labels: 4.0.6, bug, status: low

#15029 Rollback the regression changes for Phalcon\Mvc\Model\Query::_prepareSelect
  CHANGELOG-4.0.md
  ext/phalcon/mvc/model/query.zep.c
  phalcon/Mvc/Model/Query.zep
  tests/database/Mvc/Model/Query/GetSqlCest.php
Labels: 4.0.6, bug, status: low

#15030 Fixed SerializerInterface usage for result-sets
  CHANGELOG-4.0.md
  ext/phalcon/mvc/model/resultset/complex.zep.c
  ext/phalcon/mvc/model/resultset/simple.zep.c
  phalcon/Mvc/Model/Resultset/Complex.zep
  phalcon/Mvc/Model/Resultset/Simple.zep
  tests/_data/fixtures/Traits/DiTrait.php
  tests/_support/Helper/Unit.php
  tests/database/Mvc/Model/Resultset/Complex/UnserializeCest.php
  tests/database/Mvc/Model/Resultset/Simple/UnserializeCest.php
  tests/tocheck-database/Mvc/Model/Resultset/Complex/UnserializeCest.php
  tests/tocheck-database/Mvc/Model/Resultset/Simple/UnserializeCest.php
Labels: 4.0.6, bug, status: medium

#15037 Removed InterpolatorFactory::${mapper,services}
  CHANGELOG-4.0.md
  ext/phalcon/translate/interpolatorfactory.zep.c
  ext/phalcon/translate/interpolatorfactory.zep.h
  phalcon/Translate/InterpolatorFactory.zep
Labels: 4.0.6, bug, status: low
