Repository phalcon/cphalcon, pull requests merged in 2020-10, with the labels that each got.

#15086 Feature/dialect support comment
  phalcon/Db/Adapter/Pdo/Mysql.zep
  phalcon/Db/Adapter/Pdo/Postgresql.zep
  phalcon/Db/Column.zep
  phalcon/Db/Dialect/Mysql.zep
  phalcon/Db/Dialect/Postgresql.zep
  tests/_data/fixtures/Db/mysql/example8.sql
  tests/_data/fixtures/Db/postgresql/example10.sql
  tests/_data/fixtures/Traits/_tocheck/DialectTrait.php
  tests/database/Db/Column/GetCommentCest.php
  tests/integration/Db/Dialect/Mysql/CreateTableCest.php
  tests/integration/Db/Dialect/Mysql/ModifyColumnCest.php
  tests/tocheck-database/Db/Dialect/Mysql/CreateTableCest.php
  tests/tocheck-database/Db/Dialect/Mysql/DescribeColumnsCest.php
  tests/tocheck-database/Db/Dialect/Mysql/ModifyColumnCest.php
  tests/tocheck-database/Db/Dialect/Postgresql/CreateTableCest.php
  tests/tocheck-database/Db/Dialect/Postgresql/DescribeColumnsCest.php
  tests/tocheck-database/Db/Dialect/Postgresql/ModifyColumnCest.php
Labels: 4.1.0, enhancement

#15163 T14904 - Fix Model events order and handle beforeDelete with SoftDelete
  CHANGELOG-4.1.md
  phalcon/Mvc/Model/Manager.zep
  tests/_data/fixtures/models/Invoices.php
  tests/_data/fixtures/models/InvoicesBehavior.php
  tests/database/Mvc/Model/Behavior/SoftDeleteCest.php
  tests/database/Mvc/Model/Behavior/TimestampableCest.php
Labels: 4.1.0, bug

#15161 T14617 - Reverse column map check
  CHANGELOG-4.1.md
  phalcon/Mvc/Model.zep
  tests/_data/fixtures/models/InvoicesMap.php
  tests/database/Mvc/Model/CloneResultMapCest.php
  tests/database/Mvc/Model/FindFirstCest.php
Labels: 4.1.0, bug

#15162 T15102 - Router unicode support
  CHANGELOG-4.1.md
  phalcon/Mvc/Router/Route.zep
  tests/integration/Mvc/Router/Route/CompilePatternCest.php
Labels: 4.1.0, bug

#15173 T13938 - Lowercase relation
  tests/_data/fixtures/models/Customers.php
  tests/database/Mvc/Model/UnderscoreSetCest.php
Labels: 4.1.0, testing

#15174 T14114 - Foreign key constraint checks do not use transactions
  tests/database/Mvc/Model/DeleteCest.php
Labels: 4.1.0, testing

#15175 T13482 -Response set within dispatch:beforeException
  tests/integration/Mvc/Application/HandleCest.php
Labels: 4.1.0, testing

#15176 T15117 - Controller::initialize() is skipped
  tests/_data/fixtures/controllers/InitController.php
  tests/integration/Mvc/Application/HandleCest.php
Labels: 4.1.0, testing

#15187 #14968 - Add support of smallint in Postgresql
  phalcon/Db/Dialect/Postgresql.zep
Labels: hacktoberfest-accepted

#15198 ci: fix windows builds
  .github/workflows/build-and-test.yml
Labels: 4.1.0, testing
