Repository phalcon/cphalcon, pull requests merged in 2020-01, with the labels that each got.

#14671 Introduce a list of code owners [ci skip]
  CODE_OWNERS.TXT
Labels: 4.0.1, enhancement

#14674 #14669 - Fix alias columns in Query Builder Column map
  CHANGELOG-4.0.md
  phalcon/Mvc/Model/Resultset/Simple.zep
  tests/_data/fixtures/Traits/DiTrait.php
  tests/_data/fixtures/models/InvoicesWithColumnMap.php
  tests/integration/Mvc/Model/Resultset/Simple/ToArrayCest.php
Labels: 4.0.1, bug, status: low

#14676 Ci Setup for pecl
  .github/workflows/pecl.yml
  package.xml
Labels: 4.0.1, enhancement

#14692 Issue 14691
  CHANGELOG-4.0.md
  phalcon/Db/Adapter/Pdo/Mysql.zep
  tests/_data/assets/db/schemas/mysql_schema.sql
  tests/_data/fixtures/Traits/Db/MysqlTrait.php
Labels: 4.0.1, bug, status: low

#14704 T13128 http2 preload 2
  CHANGELOG-4.1.md
  phalcon/Mvc/View/Engine/Volt/Compiler.zep
  phalcon/Tag.zep
  tests/integration/Mvc/View/Engine/Volt/Compiler/FunctionCallCest.php
  tests/unit/Tag/PreloadCest.php
Labels: 4.1.0, documentation, new feature request

#14712 T14711 volt join
  CHANGELOG-4.0.md
  phalcon/Mvc/View/Engine/Volt/Compiler.zep
  tests/integration/Mvc/View/Engine/Volt/Compiler/CompileStringCest.php
Labels: 4.0.3, bug, status: low

#14728 [4.0.x] - Docblock updates
  phalcon/Filter/Sanitize/UpperWords.zep
  phalcon/Storage/Adapter/Redis.zep
Labels: 4.0.3, enhancement

#14742 Update generate-api-docs.php [ci skip]
  tests/_ci/generate-api-docs.php
Labels: 4.0.3, documentation

#14757 Fixed issue 14756 - File not found if path contains .
  CHANGELOG-4.0.md
  phalcon/Config/ConfigFactory.zep
  tests/_data/assets/config/config-with.in-file.name.ini
  tests/unit/Config/ConfigFactory/LoadCest.php
Labels: 4.0.3, bug, status: low

#14771 Bump Zephir to 0.12.16
  .travis.yml
  appveyor.yml
  tests/_ci/nanobox/boxfile.7.2.yml
  tests/_ci/nanobox/boxfile.7.3.yml
Labels: 4.0.3

#14758 #14730 - Add tests for findFirst() with primary key as a string
  phalcon/Mvc/Model/Query/Builder.zep
  tests/_data/fixtures/Migrations/StringPrimaryMigration.php
  tests/_data/fixtures/models/ModelWithStringPrimary.php
  tests/integration/Mvc/ModelCest.php
Labels: 4.0.4, status: low

#14790 Bugfix #14787
  CHANGELOG-4.0.md
  phalcon/Cli/Console.zep
Labels: 4.0.4, bug, status: medium
