Repository phalcon/cphalcon, pull requests merged in 2020-02, with the labels that each got.

#14798 #14797 - Column default value
  CHANGELOG-4.0.md
  phalcon/Db/Dialect/Mysql.zep
  tests/_data/fixtures/Db/mysql/example7.sql
  tests/integration/Db/Dialect/Mysql/CreateTableCest.php
Labels: 4.0.4, bug, status: medium

#14841 Add test case in AssignCest class [PHP 7.4]
  tests/database/Mvc/Model/AssignCest.php
Labels: testing

#14846 Unittest
  tests/README.md
  tests/unit/Assets/Collection/ConstructCest.php
Labels: 4.0.4, testing

#14716 Fix ManyToMany select query across multiple schemas
  phalcon/Mvc/Model/Query.zep
Labels: 4.0.5, Tests needed

#14854 Test ManyToMany with multiple schemas
  .github/workflows/build-and-test.yml
  .github/workflows/codecoverage.yml
  ext/kernel/filter.c
  ext/phalcon/debug/dump.zep.c
  ext/phalcon/http/message/response.zep.c
  ext/phalcon/http/response.zep.c
  ext/phalcon/mvc/model/query.zep.c
  ext/php_phalcon.h
  tests/_ci/.env.default
  tests/_ci/nanobox/.env.example
  tests/_data/assets/schemas/mysql.sql
  tests/_data/assets/schemas/pgsql.sql
  tests/_data/assets/schemas/sqlite.sql
  tests/_data/fixtures/Migrations/RobotMigration.php
  tests/_data/fixtures/Migrations/RobotPartMigration.php
  tests/_data/fixtures/Migrations/RobotToRobotPartMigration.php
  tests/_data/fixtures/models/Robot.php
  tests/_data/fixtures/models/RobotPart.php
  tests/_data/fixtures/models/RobotToRobotPart.php
  tests/_envs/mysql.yml
  tests/_envs/pgsql.yml
  tests/database/Mvc/Model/Criteria/JoinCest.php
Labels: 4.0.5

#14872 T14871 lazy loader
  CHANGELOG-4.0.md
  CHANGELOG-4.1.md
  phalcon/Mvc/Micro/LazyLoader.zep
  tests/integration/Mvc/Micro/GetActiveHandlerCest.php
  tests/integration/Mvc/Micro/LazyLoader/GetHandlerCest.php
  tests/unit/Filter/Filter/SanitizeMultipleCest.php
Labels: 4.1.0, new feature request

#14860 #14858 - Check folder name ending with period
  tests/integration/Storage/Adapter/Stream/GetSetCest.php
  tests/unit/Helper/Str/DirFromFileCest.php
Labels: 4.0.5

#14876 #14862 - Swap condition if column allows null values in PostgreSQL
  .github/workflows/build-and-test.yml
  CHANGELOG-4.0.md
  phalcon/Db/Adapter/Pdo/Postgresql.zep
  tests/_data/assets/schemas/pgsql.sql
  tests/_data/fixtures/Migrations/AbstractMigration.php
  tests/_data/fixtures/Migrations/CustomersMigration.php
  tests/database/Mvc/Model/CreateCest.php
  tests/database/Mvc/Model/UpdateCest.php
Labels: 4.0.5, bug, status: medium

#14881 #14880 - Fix column default ON UPDATE
  CHANGELOG-4.0.md
  phalcon/Db/Dialect/Mysql.zep
  tests/integration/Db/Dialect/Mysql/AddColumnCest.php
  tests/integration/Db/Dialect/Mysql/CreateTableCest.php
  tests/integration/Db/Dialect/Mysql/ModifyColumnCest.php
  tests/tocheck-database/Db/Adapter/Pdo/Mysql/AddColumnCest.php
  tests/tocheck-database/Db/Adapter/Pdo/Mysql/CreateTableCest.php
  tests/tocheck-database/Db/Adapter/Pdo/Mysql/ModifyColumnCest.php
Labels: 4.0.5, bug, status: medium
