Repository phalcon/cphalcon, pull requests merged in 2021-11, with the labels that each got.

#15750 T15637 sql variables array
  CHANGELOG-5.0.md
  phalcon/Db/Adapter/AbstractAdapter.zep
  tests/database/Db/Adapter/GetSQLVariablesCest.php
Labels: breaks bc, bug, status: medium, 5.0

#15759 T15438 Added Phalcon\Forms\Form::getFilteredValue()
  CHANGELOG-5.0.md
  phalcon/Forms/Form.zep
  tests/integration/Forms/Form/GetFilteredValueCest.php
Labels: bug, status: medium, 5.0

#15760 T15739 and T15356
  tests/database/Mvc/Model/AssignCest.php
  tests/database/Mvc/Model/FindFirstCest.php
Labels: bug, status: medium, 5.0

#15764 T15361 find toarray
  CHANGELOG-5.0.md
  phalcon/Db/Adapter/Pdo/Mysql.zep
  tests/database/Db/Adapter/Pdo/ConnectCest.php
  tests/database/Mvc/Model/ToArrayCest.php
Labels: bug, status: low, 5.0

#15766 T15731 password hash
  CHANGELOG-5.0.md
  phalcon/Encryption/Crypt/PadFactory.zep.orig
  phalcon/Encryption/Security.zep
  tests/unit/Encryption/Security/CheckHashCest.php
  tests/unit/Encryption/Security/CheckTokenCest.php
  tests/unit/Encryption/Security/GetHashInformationCest.php
  tests/unit/Encryption/Security/GetSetWorkFactorCest.php
  tests/unit/Encryption/Security/IsLegacyHashCest.php
Labels: new feature request, 5.0

#15769 T14928 Fixed allow empty file validation
  CHANGELOG-5.0.md
  phalcon/Validation/Validator/File.zep
  tests/integration/Validation/Validator/File/CustomMessagesCest.php
Labels: bug, status: medium, 5.0

#15770 T15067 Fix controller name parsing route
  CHANGELOG-5.0.md
  phalcon/Mvc/Router/Route.zep
  tests/integration/Mvc/Router/Route/GetRoutePathsCest.php
Labels: breaks bc, bug, status: low, 5.0

#15772 T15515 Fix allow empty validation
  CHANGELOG-5.0.md
  phalcon/Validation/AbstractValidator.zep
  phalcon/Validation/Validator/Alnum.zep
  phalcon/Validation/Validator/Alpha.zep
  phalcon/Validation/Validator/Between.zep
  phalcon/Validation/Validator/Callback.zep
  phalcon/Validation/Validator/Confirmation.zep
  phalcon/Validation/Validator/CreditCard.zep
  phalcon/Validation/Validator/Date.zep
  phalcon/Validation/Validator/Digit.zep
  phalcon/Validation/Validator/Email.zep
  phalcon/Validation/Validator/ExclusionIn.zep
  phalcon/Validation/Validator/Identical.zep
  phalcon/Validation/Validator/InclusionIn.zep
  phalcon/Validation/Validator/Ip.zep
  phalcon/Validation/Validator/Numericality.zep
  phalcon/Validation/Validator/PresenceOf.zep
  phalcon/Validation/Validator/Regex.zep
  phalcon/Validation/Validator/StringLength/Max.zep
  phalcon/Validation/Validator/StringLength/Min.zep
  phalcon/Validation/Validator/Url.zep
  tests/integration/Mvc/Router/HandleCest.php
  tests/integration/Validation/AllowEmptyCest.php
  tests/integration/Validation/Validator/Callback/ValidateCest.php
Labels: bug, status: medium, 5.0

#15752 T14203 fix form validator get value
  CHANGELOG-5.0.md
  phalcon/Forms/Form.zep
  phalcon/Validation.zep
  tests/_data/fixtures/models/EntityWithGetter.php
  tests/_data/fixtures/models/EntityWithHook.php
  tests/_data/fixtures/models/EntityWithPublic.php
  tests/database/Mvc/Model/AssignCest.php
  tests/database/Mvc/Model/AverageCest.php
  tests/integration/Forms/Form/BindCest.php
  tests/integration/Validation/AllowEmptyCest.php
  tests/integration/Validation/GetValueByDataCest.php
  tests/integration/Validation/GetValueByEntityCest.php
  tests/integration/Validation/Validator/Callback/ValidateCest.php
Labels: breaks bc, bug, status: medium, 5.0

#15781 T15413 Fixed raw value bug in lowupdate
  CHANGELOG-5.0.md
  phalcon/Mvc/Model.zep
Labels: bug, 5.0

#15780 T15571 Add serialization of models dirty state
  CHANGELOG-5.0.md
  phalcon/Mvc/Model.zep
  tests/database/Mvc/Model/SerializeCest.php
  tests/database/Mvc/Model/UnserializeCest.php
Labels: bug, status: low, 5.0

#15793 T15785 change exists to has
  CHANGELOG-5.0.md
  composer.lock
  ext/phalcon/mvc/model.zep.c
  ext/phalcon/mvc/model.zep.h
  ext/phalcon/mvc/model/manager.zep.c
  ext/phalcon/mvc/model/manager.zep.h
  ext/phalcon/mvc/model/managerinterface.zep.c
  ext/phalcon/mvc/model/managerinterface.zep.h
  ext/phalcon/mvc/model/metadata/stream.zep.c
  ext/phalcon/mvc/model/query.zep.c
  ext/phalcon/mvc/view.zep.c
  ext/phalcon/mvc/view.zep.h
  ext/phalcon/translate/adapter/abstractadapter.zep.c
  ext/phalcon/translate/adapter/adapterinterface.zep.c
  ext/phalcon/translate/adapter/adapterinterface.zep.h
  ext/phalcon/translate/adapter/csv.zep.c
  ext/phalcon/translate/adapter/csv.zep.h
  ext/phalcon/translate/adapter/gettext.zep.c
  ext/phalcon/translate/adapter/gettext.zep.h
  ext/phalcon/translate/adapter/nativearray.zep.c
  ext/phalcon/translate/adapter/nativearray.zep.h
  phalcon/Mvc/Model.zep
  phalcon/Mvc/Model/Manager.zep
  phalcon/Mvc/Model/ManagerInterface.zep
  phalcon/Mvc/View.zep
  phalcon/Translate/Adapter/AbstractAdapter.zep
  phalcon/Translate/Adapter/AdapterInterface.zep
  phalcon/Translate/Adapter/Csv.zep
  phalcon/Translate/Adapter/Gettext.zep
  phalcon/Translate/Adapter/NativeArray.zep
  tests/unit/Assets/Collection/IsSetIsLocalCest.php
  tests/unit/Encryption/Crypt/PadFactory/NewInstanceCest.php
  tests/unit/Encryption/Crypt/Padding/AnsiCest.php
  tests/unit/Encryption/Crypt/Padding/Iso10126Cest.php
  tests/unit/Encryption/Crypt/Padding/IsoIekCest.php
  tests/unit/Encryption/Crypt/Padding/NoopCest.php
  tests/unit/Encryption/Crypt/Padding/Pkcs7Cest.php
  tests/unit/Encryption/Crypt/Padding/SpaceCest.php
  tests/unit/Encryption/Crypt/Padding/ZeroCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/CountCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/GetCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/GetIteratorCest.php
  tests/unit/Translate/Adapter/Csv/HasCest.php
  tests/unit/Translate/Adapter/Gettext/HasCest.php
  tests/unit/Translate/Adapter/NativeArray/HasCest.php
Labels: new feature request, 5.0

#15794 T15603 Fix dispatcher setParams during dispatch loop
  CHANGELOG-5.0.md
  phalcon/Dispatcher/AbstractDispatcher.zep
Labels: bug, 5.0

#15803 T15796 move container
  CHANGELOG-5.0.md
  ext/config.m4
  ext/config.w32
  ext/phalcon.c
  ext/phalcon.h
  ext/phalcon/container.zep.h
  ext/phalcon/container/container.zep.c
  ext/phalcon/container/container.zep.h
  phalcon/Container/Container.zep
  tests/unit/Container/ConstructCest.php
  tests/unit/Container/GetCest.php
  tests/unit/Container/HasCest.php
Labels: new feature request, 5.0

#15795 T15603 before execute route
  tests/_data/fixtures/controllers/DispatcherParametersController.php
  tests/unit/Dispatcher/GetActionSuffixCest.php
  tests/unit/Dispatcher/GetDefaultNamespaceCest.php
  tests/unit/Dispatcher/GetHandlerClassCest.php
  tests/unit/Dispatcher/GetHandlerSuffixCest.php
  tests/unit/Dispatcher/GetModuleNameCest.php
  tests/unit/Dispatcher/GetNamespaceNameCest.php
  tests/unit/Dispatcher/GetParamCest.php
  tests/unit/Dispatcher/GetParamsCest.php
  tests/unit/Dispatcher/GetReturnedValueCest.php
  tests/unit/Dispatcher/GetSetActionSuffixCest.php
  tests/unit/Dispatcher/GetSetDICest.php
  tests/unit/Dispatcher/GetSetDefaultNamespaceCest.php
  tests/unit/Dispatcher/GetSetEventsManagerCest.php
  tests/unit/Dispatcher/GetSetHandlerSuffixCest.php
  tests/unit/Dispatcher/GetSetHasParamCest.php
  tests/unit/Dispatcher/GetSetModuleNameCest.php
  tests/unit/Dispatcher/GetSetNamespaceNameCest.php
  tests/unit/Dispatcher/GetSetParamsCest.php
  tests/unit/Dispatcher/GetSetReturnedValueCest.php
  tests/unit/Dispatcher/HasParamCest.php
  tests/unit/Dispatcher/SetActionSuffixCest.php
  tests/unit/Dispatcher/SetDefaultNamespaceCest.php
  tests/unit/Dispatcher/SetHandlerSuffixCest.php
  tests/unit/Dispatcher/SetModuleNameCest.php
  tests/unit/Dispatcher/SetNamespaceNameCest.php
  tests/unit/Dispatcher/SetParamCest.php
  tests/unit/Dispatcher/SetParamsCest.php
  tests/unit/Dispatcher/SetReturnedValueCest.php
Labels: bug, status: medium, 5.0

#15806 T15805 missing helpers
  CHANGELOG-5.0.md
  phalcon/Support/HelperFactory.zep
  tests/unit/Support/HelperFactory/NewInstanceCest.php
Labels: bug, status: low, 5.0
