Repository phalcon/cphalcon, pull requests merged in 2021-05, with the labels that each got.

#15455 #15074 - Change return from `array` to `ResultsetInterface` in Model Paginator
  CHANGELOG-5.0.md
  phalcon/Paginator/Adapter/Model.zep
  tests/database/Paginator/Adapter/Model/PaginateCest.php
Labels: 5.0, breaks bc, enhancement

#15454 T14764 gettext setlocale 2
  CHANGELOG-5.0.md
  docker/7.4/Dockerfile
  docker/8.0/Dockerfile
  phalcon/Translate/Adapter/Gettext.zep
  tests/_data/assets/config/factory.ini
  tests/_data/fixtures/Traits/TranslateGettextTrait.php
  tests/unit/Translate/Adapter/Gettext/ConstructCest.php
  tests/unit/Translate/Adapter/Gettext/GetSetLocaleCest.php
  tests/unit/Translate/TranslateFactory/LoadCest.php
Labels: 5.0, bug

#15475 Add workflow for docker
  .github/workflows/build-docker.yml
  .gitignore
  CHANGELOG-5.0.md
  composer.lock
  docker/7.4/Dockerfile
  docker/8.0/Dockerfile
Labels: 5.0, enhancement

#15479 #15363 - Fix db delete with passed `bindTypes`
  CHANGELOG-5.0.md
  phalcon/DataMapper/Query/AbstractConditions.zep
  phalcon/Db/Adapter/AbstractAdapter.zep
  phalcon/Db/Adapter/AdapterInterface.zep
  tests/database/Db/Adapter/Pdo/DeleteCest.php
  tests/database/Db/Adapter/Pdo/QueryCest.php
Labels: 5.0, bug, status: high

#15487 T15484 redis connect timeout
  CHANGELOG-5.0.md
  phalcon/Storage/Adapter/Redis.zep
  tests/integration/Cache/Adapter/Redis/DecrementCest.php
  tests/integration/Cache/Adapter/Redis/IncrementCest.php
  tests/integration/Storage/Adapter/Redis/DecrementCest.php
  tests/integration/Storage/Adapter/Redis/IncrementCest.php
Labels: 5.0, bug, documentation, status: medium

#15488 #15486 - Change `bindCounts` argument to array type
  CHANGELOG-5.0.md
  phalcon/Db/Dialect.zep
  phalcon/Db/DialectInterface.zep
  phalcon/Mvc/Model.zep
  phalcon/Mvc/Model/Query/Builder.zep
  phalcon/Mvc/ModelInterface.zep
  tests/database/Mvc/Model/CountCest.php
Labels: 5.0, bug
