Repository phalcon/cphalcon, pull requests merged in 2021-03, with the labels that each got.

#15342 T15240 igbinary serialize numbers
  CHANGELOG-5.0.md
  package.xml
  phalcon/Storage/Serializer/Igbinary.zep
  tests/database/Mvc/Model/Behavior/SoftDeleteCest.php
  tests/database/Mvc/Model/Behavior/TimestampableCest.php
  tests/integration/Storage/Serializer/Igbinary/SerializeCest.php
Labels: 5.0, bug, status: medium

#15348 update declarions of function getEventsManager() to allow null return
  CHANGELOG-5.0.md
  phalcon/Acl/Adapter/AbstractAdapter.zep
  phalcon/Application/AbstractApplication.zep
  phalcon/Db/Adapter/AbstractAdapter.zep
  phalcon/Dispatcher/AbstractDispatcher.zep
  phalcon/Http/Response.zep
  phalcon/Loader.zep
  phalcon/Mvc/Model/Manager.zep
  phalcon/Mvc/Router.zep
Labels: 5.0, bug, status: low

#15351 T15345 underscore methods
  CHANGELOG-5.0.md
  docker/7.4/Dockerfile
  docker/8.0/Dockerfile
  phalcon/DataMapper/Pdo/Profiler/Profiler.zep
  phalcon/Db/Profiler.zep
  phalcon/Http/Cookie.zep
  phalcon/Mvc/Model.zep
  phalcon/Mvc/Model/Manager.zep
  phalcon/Mvc/Model/Query.zep
  phalcon/Mvc/View/Engine/Volt/Compiler.zep
  tests/integration/Mvc/View/Engine/Volt/Compiler/CompileCacheCest.php
  tests/unit/Http/Response/Cookies/GetSetCest.php
Labels: 5.0, enhancement, new feature request

#15353 fixing Flash\Session::has() returning always true
  CHANGELOG-5.0.md
  phalcon/Flash/Session.zep
  tests/unit/Flash/Session/HasCest.php
Labels: 5.0, bug, status: low
