Repository phalcon/cphalcon, pull requests merged in 2021-08, with the labels that each got.

#15610 Improve PSR detection via Zephir's Dynamic Class Entries detection
  .github/workflows/build-and-test.yml
  .github/workflows/codecoverage.yml
  .github/workflows/static-code-analysis.yml
  build/config/phalcon_c_header.php
  composer.json
  composer.lock
  docker/7.4/.bashrc
  docker/8.0/.bashrc
  tests/unit/Support/Debug/DebugVarCest.php
  tests/unit/Support/Debug/GetCssSourcesCest.php
  tests/unit/Support/Debug/GetJsSourcesCest.php
  tests/unit/Support/Debug/GetVersionCest.php
  tests/unit/Support/Debug/ListenExceptionsCest.php
  tests/unit/Support/Debug/ListenLowSeverityCest.php
  tests/unit/Support/Debug/OnUncaughtExceptionCest.php
  tests/unit/Support/Debug/OnUncaughtLowSeverityCest.php
  tests/unit/Support/Debug/RenderHtmlCest.php
  tests/unit/Support/Debug/SetShowBackTraceCest.php
  tests/unit/Support/Debug/SetShowFilesCest.php
  tests/unit/Support/Debug/SetUriCest.php
Labels: enhancement, 5.0

#15506 T15504 psr 1.1
  CHANGELOG-5.0.md
  package.xml
  phalcon/Container.zep
  tests/unit/Container/ConstructCest.php
  tests/unit/Container/GetCest.php
  tests/unit/Container/HasCest.php
Labels: new feature request, 5.0

#15616 T15615 http method status constants
  CHANGELOG-5.0.md
  phalcon/Http/Message/AbstractRequest.zep
  phalcon/Http/Message/Request.zep
  phalcon/Http/Message/RequestMethodInterface.zep
  phalcon/Http/Message/Response.zep
  phalcon/Http/Message/ResponseStatusCodeInterface.zep
  phalcon/Http/Message/ServerRequest.zep
  phalcon/Http/Message/ServerRequestFactory.zep
  phalcon/Http/Request.zep
  phalcon/Http/RequestInterface.zep
  phalcon/Http/Response.zep
Labels: new feature request, 5.0

#15618 T15292 flash css classes
  CHANGELOG-5.0.md
  phalcon/Flash/AbstractFlash.zep
  tests/unit/Flash/Direct/SetCssIconClassesCest.php
Labels: new feature request, 5.0

#15627 #15625 - Add test case v4.1
  tests/_data/assets/schemas/mysql.sql
  tests/_data/assets/schemas/pgsql.sql
  tests/_data/assets/schemas/sqlite.sql
  tests/_data/fixtures/Migrations/SettersMigration.php
  tests/_data/fixtures/Traits/DiTrait.php
  tests/_data/fixtures/models/Setters.php
  tests/_support/Helper/Database.php
  tests/database/Mvc/Model/UpdateCest.php
Labels: testing

#15626 #15625 - Add test case
  .github/workflows/static-code-analysis.yml
  composer.json
  composer.lock
  tests/_data/assets/schemas/mysql.sql
  tests/_data/assets/schemas/pgsql.sql
  tests/_data/assets/schemas/sqlite.sql
  tests/_data/fixtures/Migrations/SettersMigration.php
  tests/_data/fixtures/models/Setters.php
  tests/database/Mvc/Model/UpdateCest.php
  tests/unit/Flash/Direct/SetCssIconClassesCest.php
Labels: testing

#15629 Set default di in `getDI()`
  .ci/install-php-extensions.sh
  CHANGELOG-5.0.md
  phalcon/Di/Injectable.zep
  tests/unit/Di/GetDICest.php
Labels: enhancement, 5.0
