Repository phalcon/cphalcon, pull requests merged in 2021-09, with the labels that each got.

#15639 T15638 logger adapter serialize 5
  CHANGELOG-5.0.md
  composer.lock
  phalcon/Logger/Adapter/AbstractAdapter.zep
  tests/unit/Logger/Adapter/Noop/SerializeUnserializeCest.php
  tests/unit/Logger/Adapter/Stream/BeginCest.php
  tests/unit/Logger/Adapter/Stream/CloseCest.php
  tests/unit/Logger/Adapter/Stream/SerializeUnserializeCest.php
  tests/unit/Logger/Adapter/Syslog/BeginCest.php
  tests/unit/Logger/Adapter/Syslog/CloseCest.php
  tests/unit/Logger/Adapter/Syslog/SerializeUnserializeCest.php
Labels: bug, status: high, 5.0

#15657 T15656 custom jwt
  CHANGELOG-5.0.md
  phalcon/Security/JWT/Builder.zep
  tests/unit/Security/JWT/Builder/AddClaimCest.php
  tests/unit/Security/JWT/Builder/ConstructCest.php
  tests/unit/Security/JWT/Builder/GetClaimsCest.php
  tests/unit/Security/JWT/Builder/GetHeadersCest.php
  tests/unit/Security/JWT/Builder/GetSetAudienceCest.php
  tests/unit/Security/JWT/Builder/GetSetContentTypeCest.php
  tests/unit/Security/JWT/Builder/GetSetExpirationTimeCest.php
  tests/unit/Security/JWT/Builder/GetSetIdCest.php
  tests/unit/Security/JWT/Builder/GetSetIssuedAtCest.php
  tests/unit/Security/JWT/Builder/GetSetIssuerCest.php
  tests/unit/Security/JWT/Builder/GetSetNotBeforeCest.php
  tests/unit/Security/JWT/Builder/GetSetPassphraseCest.php
  tests/unit/Security/JWT/Builder/GetSetSubjectCest.php
  tests/unit/Security/JWT/Builder/GetTokenCest.php
  tests/unit/Security/JWT/Builder/InitCest.php
  tests/unit/Security/JWT/Signer/Hmac/ConstructCest.php
  tests/unit/Security/JWT/Signer/Hmac/GetAlgHeaderCest.php
  tests/unit/Security/JWT/Signer/Hmac/GetAlgorithmCest.php
  tests/unit/Security/JWT/Signer/Hmac/SignCest.php
  tests/unit/Security/JWT/Signer/Hmac/VerifyCest.php
  tests/unit/Security/JWT/Signer/None/ConstructCest.php
  tests/unit/Security/JWT/Signer/None/GetAlgHeaderCest.php
  tests/unit/Security/JWT/Signer/None/GetAlgorithmCest.php
  tests/unit/Security/JWT/Signer/None/SignCest.php
  tests/unit/Security/JWT/Signer/None/VerifyCest.php
  tests/unit/Security/JWT/Token/Item/ConstructCest.php
  tests/unit/Security/JWT/Token/Item/GetCest.php
  tests/unit/Security/JWT/Token/Item/HasCest.php
  tests/unit/Security/JWT/Token/Item/UnderscoreCallCest.php
  tests/unit/Security/JWT/Token/Parser/ParseCest.php
  tests/unit/Security/JWT/Token/Signature/ConstructCest.php
  tests/unit/Security/JWT/Token/Signature/UnderscoreCallCest.php
  tests/unit/Security/JWT/Token/Token/ConstructCest.php
  tests/unit/Security/JWT/Token/Token/GetClaimsCest.php
  tests/unit/Security/JWT/Token/Token/GetHeadersCest.php
  tests/unit/Security/JWT/Token/Token/GetPayloadCest.php
  tests/unit/Security/JWT/Token/Token/GetSignatureCest.php
  tests/unit/Security/JWT/Token/Token/GetTokenCest.php
  tests/unit/Security/JWT/Validator/ConstructCest.php
  tests/unit/Security/JWT/Validator/SetTokenCest.php
  tests/unit/Security/JWT/Validator/ValidateAudienceCest.php
  tests/unit/Security/JWT/Validator/ValidateExpirationCest.php
  tests/unit/Security/JWT/Validator/ValidateIdCest.php
  tests/unit/Security/JWT/Validator/ValidateIssuedAtCest.php
  tests/unit/Security/JWT/Validator/ValidateIssuerCest.php
  tests/unit/Security/JWT/Validator/ValidateNotBeforeCest.php
  tests/unit/Security/JWT/Validator/ValidateSignatureCest.php
Labels: new feature request, 5.0

#15660 #15659 - Adjust db adapter interface
  CHANGELOG-5.0.md
  phalcon/Db/Adapter/AdapterInterface.zep
  phalcon/Db/Adapter/Pdo/AbstractPdo.zep
  phalcon/Db/Adapter/Pdo/Postgresql.zep
  phalcon/Db/Adapter/Pdo/Sqlite.zep
Labels: enhancement, bug, 5.0

#15666 #15665 - Update package.xml
  package.xml
Labels: enhancement, 5.0

#15680 #15678 - Update Zephir parser installation process and CI workflows
  .ci/install-zephir.sh
  .github/workflows/build-and-test.yml
  .github/workflows/build-docker.yml
  .github/workflows/install-phalcon.yml
  .github/workflows/packagecloud-cleanup.yml
  .github/workflows/static-code-analysis.yml
  composer.lock
  docker/7.4/.bashrc
  docker/7.4/Dockerfile
  docker/8.0/.bashrc
  docker/8.0/Dockerfile
Labels: enhancement, 5.0

#15686 #15553 - Fix Query::getExpression return type
  CHANGELOG-5.0.md
  phalcon/Mvc/Model/Query.zep
  tests/unit/Mvc/Model/Query/GetExpressionCest.php
Labels: bug, 5.0
