Repository phalcon/cphalcon, pull requests merged in 2021-04, with the labels that each got.

#15383 T15249 profiler time
  .github/workflows/build-and-test.yml
  .travis.yml
  BACKERS.md
  CHANGELOG-5.0.md
  phalcon/Db/Profiler.zep
  phalcon/Db/Profiler/Item.zep
  tests/database/Db/Profiler/Item/GetTotalElapsedNanoMicroSecondsCest.php
  tests/database/Db/Profiler/Item/GetTotalElapsedSecondsCest.php
Labels: 5.0, bug, status: medium

#15385 T15249 profiler time
  .travis.yml
  CHANGELOG-5.0.md
  phalcon/Db/Profiler.zep
  phalcon/Db/Profiler/Item.zep
  tests/database/Db/Profiler/Item/GetTotalElapsedNanoMicroSecondsCest.php
  tests/database/Db/Profiler/Item/GetTotalElapsedSecondsCest.php
Labels: 5.0, bug, status: medium

#15380 T15286 serverrequestfactory load parameters
  CHANGELOG-5.0.md
  docker/7.4/.bashrc
  docker/7.4/Dockerfile
  docker/8.0/.bashrc
  phalcon/Http/Message/ServerRequestFactory.zep
  tests/unit/Http/Cookie/CookieCest.php
  tests/unit/Http/Message/ServerRequestFactory/LoadCest.php
Labels: 5.0, bug, status: medium

#15389 Bugfix | Windows builds
  .ci/appveyor.psm1
  .ci/vsenv.bat
  .ci/win-ci-tools.psm1
  .github/workflows/build-and-test.yml
  .github/workflows/codecoverage.yml
  build/_resource/config/config.w32
  build/php7/32bits/config.w32
  build/php7/64bits/config.w32
  build/php7/safe/config.w32
  build/php8/32bits/config.w32
  build/php8/64bits/config.w32
  build/php8/safe/config.w32
  ext/config.w32
  ext/phalcon/datamapper/pdo/profiler/profiler.zep.c
  ext/phalcon/http/message/abstractmessage.zep.c
  ext/phalcon/http/message/abstractrequest.zep.c
  tests/unit/Acl/Adapter/Memory/AllowCest.php
  tests/unit/Acl/Adapter/Memory/IsAllowedCest.php
  tests/unit/Image/ImageFactory/NewInstanceCest.php
Labels: 5.0, bug, status: high

#15376 T14933 session handler set get adapter
  phalcon/Session/Manager.zep
  tests/_data/fixtures/Session/ExtendedManager.php
  tests/integration/Session/Manager/ConstructCest.php
Labels: 5.0, bug, external dependency

#15392 Feature | GitHub actions only
  .ci/appveyor.psm1
  .ci/travis.ini
  .github/workflows/build-and-test.yml
  .travis.yml
  README.md
  appveyor.yml
  tests/README.md
Labels: 5.0, enhancement

#15401 test(logger/formatter/line): added test with a different line format
  phalcon/Logger.zep
  tests/_data/fixtures/Traits/LoggerTrait.php
  tests/unit/Logger/Logger/ConstructCest.php
  tests/unit/Logger/Logger/LogCest.php
Labels: 5.0, bug, status: unverified

#15414 T14927 binary varbinary mysql
  .ci/export-variables.sh
  .github/workflows/build-and-test.yml
  .github/workflows/codecoverage.yml
  CHANGELOG-5.0.md
  README.md
  phalcon/Db/Adapter/Pdo/Mysql.zep
  phalcon/Db/Column.zep
  tests/README.md
  tests/_bootstrap.php
  tests/_ci/nanobox/.env.example
  tests/_ci/nanobox/boxfile.7.2.yml
  tests/_ci/nanobox/boxfile.7.3.yml
  tests/_ci/nanobox/boxfile.7.4.yml
  tests/_ci/nanobox/setup-dbs-nanobox.sh
  tests/_config/.env.default
  tests/_config/.env.docker
  tests/_config/functions.php
  tests/_config/generate-api-docs.php
  tests/_config/generate-db-schemas.php
  tests/_config/generate-test-stubs.php
  tests/_data/assets/db/schemas/mysql_schema.sql
  tests/_data/assets/schemas/mysql.sql
  tests/_data/assets/schemas/pgsql.sql
  tests/_data/assets/schemas/sqlite.sql
  tests/_data/fixtures/Migrations/DialectMigration.php
  tests/database/Db/Adapter/Pdo/DescribeColumnsCest.php
  tests/database/Db/Adapter/Pdo/ExecInsertCest.php
Labels: 5.0, enhancement

#15416 T15415 orderby interface 2
  CHANGELOG-5.0.md
  phalcon/Mvc/Model/Query/BuilderInterface.zep
  tests/_data/fixtures/Traits/RecordsTrait.php
  tests/database/Db/Adapter/Pdo/DescribeColumnsCest.php
  tests/database/Db/Adapter/Pdo/ExecInsertCest.php
  tests/database/Mvc/Model/Query/Builder/OrderByCest.php
  tests/database/Mvc/Model/Query/GetSqlCest.php
  tests/unit/Logger/Logger/LogCest.php
Labels: 5.0, breaks bc, bug, status: high

#15418 test(image/adapter/gd): added test for text with font
  .github/workflows/build-and-test.yml
  .github/workflows/codecoverage.yml
  CHANGELOG-5.0.md
  docker/7.4/Dockerfile
  docker/8.0/Dockerfile
  phalcon/Image/Adapter/Gd.zep
  tests/_data/fixtures/Traits/GdTrait.php
  tests/unit/Image/Adapter/Gd/TextCest.php
Labels: 5.0, bug, status: low

#15419 T15241 - db persistent flag
  CHANGELOG-5.0.md
  phalcon/Db/Adapter/Pdo/AbstractPdo.zep
  tests/database/Db/Adapter/Pdo/ConnectCest.php
Labels: 5.0, bug, status: medium

#15423 T15422 version top level
  CHANGELOG-5.0.md
  docker/7.4/Dockerfile
  ext/phalcon/version.zep.c
  ext/phalcon/version.zep.h
  phalcon/Cache.zep
  phalcon/Debug.zep
  phalcon/Mvc/View/Engine/Volt/Compiler.zep
  phalcon/Support/Version.zep
  tests/integration/Mvc/View/Engine/Volt/Compiler/FunctionCallCest.php
  tests/unit/Debug/GetVersionCest.php
  tests/unit/Support/Version/ConstantsCest.php
  tests/unit/Support/Version/GetCest.php
  tests/unit/Support/Version/GetIdCest.php
  tests/unit/Support/Version/GetPartCest.php
Labels: 5.0, enhancement, new feature request

#15425 4.1.1 release
  .github/workflows/build-and-test.yml
  .github/workflows/codecoverage.yml
  .travis.yml
  appveyor.yml
  boxfile.7.4.yml
  build/php7/32bits/php_phalcon.h
  build/php7/64bits/php_phalcon.h
  build/php7/safe/php_phalcon.h
  ext/config.m4
  ext/php_phalcon.h
  tests/_ci/nanobox/boxfile.7.2.yml
  tests/_ci/nanobox/boxfile.7.3.yml
  tests/_ci/nanobox/boxfile.7.4.yml
  tests/unit/Acl/Adapter/Memory/AllowCest.php
  tests/unit/Acl/Adapter/Memory/IsAllowedCest.php
Labels: 4.1.1, release

#15426 T14817 debug styling new home
  CHANGELOG-5.0.md
  ext/phalcon/debug.zep.c
  ext/phalcon/debug.zep.h
  ext/phalcon/debug/dump.zep.c
  ext/phalcon/debug/dump.zep.h
  ext/phalcon/debug/exception.zep.c
  ext/phalcon/debug/exception.zep.h
  phalcon/Support/Debug.zep
  phalcon/Support/Debug/Dump.zep
  phalcon/Support/Debug/Exception.zep
  tests/database/Db/Adapter/Pdo/ConnectCest.php
  tests/unit/Support/Debug/DebugVarCest.php
  tests/unit/Support/Debug/Dump/AllCest.php
  tests/unit/Support/Debug/Dump/ConstructCest.php
  tests/unit/Support/Debug/Dump/GetSetDetailedCest.php
  tests/unit/Support/Debug/Dump/OneCest.php
  tests/unit/Support/Debug/Dump/SetStylesCest.php
  tests/unit/Support/Debug/Dump/ToJsonCest.php
  tests/unit/Support/Debug/Dump/VariableCest.php
  tests/unit/Support/Debug/Dump/VariablesCest.php
  tests/unit/Support/Debug/GetCssSourcesCest.php
  tests/unit/Support/Debug/GetJsSourcesCest.php
  tests/unit/Support/Debug/GetVersionCest.php
  tests/unit/Support/Debug/ListenExceptionsCest.php
  tests/unit/Support/Debug/ListenLowSeverityCest.php
  tests/unit/Support/Debug/OnUncaughtExceptionCest.php
  tests/unit/Support/Debug/OnUncaughtLowSeverityCest.php
  tests/unit/Support/Debug/RenderHtmlCest.php
  tests/unit/Support/Debug/SetShowBackTraceCest.php
  tests/unit/Support/Debug/SetShowFilesCest.php
  tests/unit/Support/Debug/SetUriCest.php
Labels: 5.0, enhancement, new feature request

#15429 T15334 headers sent twice
  CHANGELOG-5.0.md
  phalcon/Http/Response/Cookies.zep
  phalcon/Http/Response/Headers.zep
  phalcon/Mvc/Application.zep
  tests/unit/Http/Response/Cookies/SendCest.php
  tests/unit/Http/Response/Headers/SendCest.php
Labels: 5.0, bug, status: medium

#15432 T15051 validator uploaded file
  CHANGELOG-5.0.md
  phalcon/Validation/Validator/File/AbstractFile.zep
Labels: 5.0, new feature request

#15437 T15436 upgrade zephir
  docker/7.4/.bashrc
  docker/8.0/.bashrc
  phalcon/Http/Request.zep
  tests/_data/fixtures/Db/QueryListener.php
  tests/unit/Http/Response/Cookies/DeleteCest.php
Labels: 5.0, bug, status: medium
