Repository phalcon/cphalcon, pull requests merged in 2022-01, with the labels that each got.

#15849 T15847 forms tagfactory
  CHANGELOG-5.0.md
  composer.json
  composer.lock
  phalcon/Di/FactoryDefault.zep
  phalcon/Forms/Element/AbstractElement.zep
  tests/integration/Forms/Element/GetSetTagFactoryCest.php
  tests/integration/Forms/Form/GetSetTagFactoryCest.php
Labels: enhancement, bug, status: high, 5.0

#15854 T15853 escaper volt
  phalcon/Mvc/View/Engine/Volt/Compiler.zep
  tests/integration/Mvc/View/Engine/Volt/Compiler/FunctionCallCest.php
Labels: bug, status: medium, 5.0

#15858 T14547 syslog phpeol
  .github/workflows/main.yml
  CHANGELOG-5.0.md
  config.json
  package.xml
  phalcon/Logger/Adapter/AbstractAdapter.zep
  phalcon/Logger/Adapter/Stream.zep
  phalcon/Support/Version.zep
Labels: bug, status: low, 5.0

#15870 #15869 - Update Mustache
  composer.json
  composer.lock
Labels: enhancement, testing, 5.0

#15875 T15850 camelize fix
  CHANGELOG-5.0.md
  phalcon/Logger/Logger.zep
  phalcon/Support/Collection.zep
  phalcon/Support/Helper/Str/KebabCase.zep
  phalcon/Support/Helper/Str/SnakeCase.zep
  tests/_data/fixtures/Traits/LoaderTrait.php
  tests/unit/Logger/LoggerFactory/LoadCest.php
  tests/unit/Support/Helper/Str/CaseCest.php
  tests/unit/Support/Helper/Str/KebabCaseCest.php
  tests/unit/Support/Helper/Str/PascalCaseCest.php
  tests/unit/Support/Helper/Str/SnakeCaseCest.php
Labels: bug, status: medium, 5.0

#15878 Dependencies update (mustache)
  composer.json
  composer.lock
Labels: bug, status: low, 5.0
