Repository phalcon/cphalcon, pull requests merged in 2022-10, with the labels that each got.

#16138 T16135 stringval flags
  CHANGELOG-5.0.md
  phalcon/Filter/Sanitize/StringVal.zep
Labels: bug, status: medium, 5.0

#16140 v5.0.3 Prep
  .github/workflows/main.yml
  CHANGELOG-5.0.md
  config.json
  ext/phalcon/filter/sanitize/stringval.zep.c
  ext/phalcon/filter/sanitize/stringval.zep.h
  ext/phalcon/html/escaper.zep.c
  ext/phalcon/support/version.zep.c
  ext/php_phalcon.h
  package.xml
  phalcon/Support/Version.zep
Labels: 5.0

#16141 Fix typo from Loader registerNamespaces
  CHANGELOG-5.0.md
Labels: documentation, 5.0

#16154 T16153 security workfactor not calculated
  CHANGELOG-5.0.md
  phalcon/Encryption/Security.zep
Labels: bug, status: medium, 5.0

#16036 [BUG] Complex Resultset double unserializing
  phalcon/Mvc/Model/Resultset/Complex.zep
Labels: bug, 5.0

#16158 T16157 mysql descripe indexes
  CHANGELOG-5.0.md
  phalcon/Db/Adapter/Pdo/Mysql.zep
  phalcon/Db/Adapter/Pdo/Sqlite.zep
Labels: bug, status: medium, 5.0

#16159 #16127 - Fix MacOS
  .github/actions/build-phalcon-mac/action.yml
  .github/workflows/main.yml
Labels: bug

#16165 Bugfix in JWT "exp" (Expiration Time) Claim validation.
  phalcon/Encryption/Security/JWT/Validator.zep
  tests/unit/Encryption/Security/JWT/Token/Token/ValidateCest.php
  tests/unit/Encryption/Security/JWT/Validator/ValidateExpirationCest.php
Labels: bug, status: high, 5.0

#16172 T16171 config insensitive
  CHANGELOG-5.0.md
  phalcon/Config/Adapter/Grouped.zep
  phalcon/Config/Config.zep
  tests/unit/Config/Config/ConfigCest.php
Labels: bug, status: medium, 5.0

#16173 T16170 strict session id syntax
  CHANGELOG-5.0.md
  phalcon/Session/Manager.zep
  tests/integration/Session/Manager/GetSetNameCest.php
  tests/integration/Session/Manager/StartCest.php
Labels: bug, status: medium, 5.0

#16178 #16177 - Unify args of `fetchAll()` with `PDOStatement::fetchAll()`
  CHANGELOG-5.0.md
  phalcon/Db/Result/PdoResult.zep
Labels: bug, status: high, 5.0

#16179 adjust default for form::label attributes
  phalcon/Forms/Form.zep
Labels: bug, status: medium, 5.0

#16187 T16097 volt render notice undefined index name
  CHANGELOG-5.0.md
  phalcon/Mvc/View/Engine/Volt/Compiler.zep
  tests/_data/fixtures/Objects/ChildObject.php
  tests/_data/fixtures/Objects/ParentObject.php
  tests/_data/fixtures/views/currentrender/subobject.volt
  tests/integration/Mvc/View/PickCest.php
  tests/integration/Mvc/View/RenderCest.php
  tests/integration/Mvc/View/Simple/RenderCest.php
Labels: bug, status: high, 5.0
