Repository phalcon/cphalcon, pull requests merged in 2022-09, with the labels that each got.

#16085 #16080 - Fix segmentation fault
  CHANGELOG-5.0.md
  phalcon/Mvc/Model.zep
Labels: bug, 5.0

#16095 T16094 JWT verify
  CHANGELOG-5.0.md
  package.xml
  phalcon/Encryption/Security/JWT/Builder.zep
  phalcon/Encryption/Security/JWT/Exceptions/UnsupportedAlgorithmException.zep
  phalcon/Encryption/Security/JWT/Exceptions/ValidatorException.zep
  phalcon/Encryption/Security/JWT/Signer/AbstractSigner.zep
  phalcon/Encryption/Security/JWT/Signer/Hmac.zep
  phalcon/Encryption/Security/JWT/Signer/None.zep
  phalcon/Encryption/Security/JWT/Signer/SignerInterface.zep
  phalcon/Encryption/Security/JWT/Token/AbstractItem.zep
  phalcon/Encryption/Security/JWT/Token/Enum.zep
  phalcon/Encryption/Security/JWT/Token/Item.zep
  phalcon/Encryption/Security/JWT/Token/Parser.zep
  phalcon/Encryption/Security/JWT/Token/Signature.zep
  phalcon/Encryption/Security/JWT/Token/Token.zep
  phalcon/Encryption/Security/JWT/Validator.zep
  phalcon/Html/Link/AbstractLink.zep
  phalcon/Html/Link/EvolvableLink.zep
  tests/unit/Encryption/Security/JWT/Validator/SetTokenCest.php
  tests/unit/Encryption/Security/JWT/Validator/ValidateAudienceCest.php
  tests/unit/Encryption/Security/JWT/Validator/ValidateExpirationCest.php
  tests/unit/Encryption/Security/JWT/Validator/ValidateIdCest.php
  tests/unit/Encryption/Security/JWT/Validator/ValidateIssuedAtCest.php
  tests/unit/Encryption/Security/JWT/Validator/ValidateIssuerCest.php
  tests/unit/Encryption/Security/JWT/Validator/ValidateNotBeforeCest.php
  tests/unit/Encryption/Security/JWT/Validator/ValidateSignatureCest.php
Labels: new feature request, 5.0

#16100 #16096 - Fix seg faults on class mock
  .github/workflows/main.yml
  CHANGELOG-5.0.md
  composer.lock
  docker/7.4/.bashrc
  docker/8.0/.bashrc
  docker/8.1/.bashrc
  ext/phalcon/annotations/collection.zep.h
  ext/phalcon/di/di.zep.h
  ext/phalcon/di/injectable.zep.c
  ext/phalcon/encryption/security/jwt/builder.zep.c
  ext/phalcon/encryption/security/jwt/exceptions/unsupportedalgorithmexception.zep.c
  ext/phalcon/encryption/security/jwt/exceptions/validatorexception.zep.c
  ext/phalcon/encryption/security/jwt/signer/abstractsigner.zep.c
  ext/phalcon/encryption/security/jwt/signer/hmac.zep.c
  ext/phalcon/encryption/security/jwt/signer/none.zep.c
  ext/phalcon/encryption/security/jwt/signer/signerinterface.zep.c
  ext/phalcon/encryption/security/jwt/token/abstractitem.zep.c
  ext/phalcon/encryption/security/jwt/token/enum.zep.c
  ext/phalcon/encryption/security/jwt/token/item.zep.c
  ext/phalcon/encryption/security/jwt/token/parser.zep.c
  ext/phalcon/encryption/security/jwt/token/signature.zep.c
  ext/phalcon/encryption/security/jwt/token/token.zep.c
  ext/phalcon/encryption/security/jwt/token/token.zep.h
  ext/phalcon/encryption/security/jwt/validator.zep.c
  ext/phalcon/encryption/security/jwt/validator.zep.h
  ext/phalcon/filter/validation/validator/digit.zep.c
  ext/phalcon/filter/validation/validator/numericality.zep.c
  ext/phalcon/flash/abstractflash.zep.c
  ext/phalcon/forms/form.zep.c
  ext/phalcon/forms/form.zep.h
  ext/phalcon/html/link/abstractlink.zep.c
  ext/phalcon/html/link/evolvablelink.zep.c
  ext/phalcon/html/tagfactory.zep.c
  ext/phalcon/logger/adapter/stream.zep.c
  ext/phalcon/messages/messages.zep.h
  ext/phalcon/mvc/micro.zep.h
  ext/phalcon/mvc/model.zep.c
  ext/phalcon/mvc/model.zep.h
  ext/phalcon/mvc/model/query.zep.c
  ext/phalcon/mvc/model/query.zep.h
  ext/phalcon/mvc/model/resultset.zep.h
  ext/phalcon/mvc/model/resultset/complex.zep.h
  ext/phalcon/mvc/model/row.zep.h
  ext/phalcon/mvc/view/engine/volt/compiler.zep.c
  ext/phalcon/storage/serializer/none.zep.h
  ext/phalcon/storage/serializer/php.zep.h
  ext/phalcon/support/collection.zep.h
  ext/phalcon/support/registry.zep.h
  ext/phalcon/translate/adapter/abstractadapter.zep.h
  ext/php_phalcon.h
  phalcon/Forms/Form.zep
  phalcon/Mvc/Model/Query.zep
  tests/MassMockTest.php
Labels: enhancement, bug, external dependency, 5.0

#16105 Improve and refactor code
  phalcon/Acl/Adapter/Memory.zep
  phalcon/Acl/Component.zep
  phalcon/Acl/Role.zep
  phalcon/Annotations/Adapter/AbstractAdapter.zep
  phalcon/Annotations/Reader.zep
  phalcon/Application/AbstractApplication.zep
  phalcon/Cli/Console.zep
  phalcon/Cli/Dispatcher.zep
  phalcon/Cli/Router.zep
  phalcon/Db/Adapter/AbstractAdapter.zep
  phalcon/Db/Adapter/Pdo/AbstractPdo.zep
  phalcon/Db/Result/PdoResult.zep
  phalcon/Di/Di.zep
  phalcon/Di/Exception/ServiceResolutionException.zep
  phalcon/Di/InitializationAwareInterface.zep
  phalcon/Di/Injectable.zep
  phalcon/Di/Service.zep
  phalcon/Di/Service/Builder.zep
  phalcon/Dispatcher/AbstractDispatcher.zep
  phalcon/Factory/AbstractConfigFactory.zep
  phalcon/Filter/Validation.zep
  phalcon/Http/Cookie.zep
  phalcon/Http/Request.zep
  phalcon/Http/Response.zep
  phalcon/Http/Response/Cookies.zep
  phalcon/Messages/Messages.zep
  phalcon/Mvc/Application.zep
  phalcon/Mvc/Dispatcher.zep
  phalcon/Mvc/Micro.zep
  phalcon/Mvc/Model.zep
  phalcon/Mvc/Router.zep
  phalcon/Mvc/Url.zep
  phalcon/Mvc/View.zep
  phalcon/Mvc/View/Engine/Php.zep
  phalcon/Mvc/View/Engine/Volt/Compiler.zep
  phalcon/Mvc/ViewBaseInterface.zep
  phalcon/Tag.zep
Labels: enhancement, 5.0

#16106 Refactor `Phalcon\Annotations\Reflection` class
  CHANGELOG-5.0.md
  phalcon/Annotations/Reflection.zep
  tests/unit/Annotations/Reflection/GetClassAnnotationsCest.php
  tests/unit/Annotations/Reflection/GetMethodsAnnotationsCest.php
  tests/unit/Annotations/Reflection/GetPropertiesAnnotationsCest.php
  tests/unit/Annotations/Reflection/GetReflectionDataCest.php
Labels: enhancement, 5.0

#16107 Adjust condition of `getDocComment()`
  phalcon/Annotations/Reader.zep
Labels: enhancement, 5.0

#16109 T16108 escaper attributes
  CHANGELOG-5.0.md
  phalcon/Html/Escaper.zep
  tests/_config/generate-api-docs.php
  tests/unit/Html/Escaper/AttributesCest.php
Labels: new feature request, 5.0

#16110 Make `Phalcon\Mvc\Model:uniqueTypes` always array
  phalcon/Mvc/Model.zep
Labels: enhancement, 5.0

#16116 T16115 jwt validate
  CHANGELOG-5.0.md
  phalcon/Encryption/Security/JWT/Token/Token.zep
  phalcon/Encryption/Security/JWT/Validator.zep
  tests/unit/Encryption/Security/JWT/Token/Token/GetClaimsCest.php
  tests/unit/Encryption/Security/JWT/Token/Token/GetHeadersCest.php
  tests/unit/Encryption/Security/JWT/Token/Token/GetPayloadCest.php
  tests/unit/Encryption/Security/JWT/Token/Token/GetSignatureCest.php
  tests/unit/Encryption/Security/JWT/Token/Token/GetTokenCest.php
  tests/unit/Encryption/Security/JWT/Token/Token/ValidateCest.php
Labels: bug, status: high, 5.0

#16124 T16123 html attributes
  CHANGELOG-5.0.md
  phalcon/Html/Escaper.zep
  phalcon/Logger/AbstractLogger.zep
  tests/unit/Html/Escaper/AttributesCest.php
Labels: bug, status: high, 5.0
