Repository phalcon/cphalcon, pull requests merged in 2022-11, with the labels that each got.

#16190 T16188 cannot fetch patch payload
  CHANGELOG-5.0.md
  phalcon/Http/Request.zep
  tests/unit/Http/Request/GetFilteredPatchCest.php
  tests/unit/Http/Request/GetPatchCest.php
Labels: new feature request, 5.0

#16191 T15956 clear form
  CHANGELOG-5.0.md
  phalcon/Acl/Adapter/AdapterInterface.zep
  phalcon/Acl/Adapter/Memory.zep
  phalcon/Assets/Asset.zep
  phalcon/Assets/Collection.zep
  phalcon/Assets/Filters/CssMin.zep
  phalcon/Assets/Filters/JsMin.zep
  phalcon/Assets/Manager.zep
  phalcon/Autoload/Loader.zep
  phalcon/Cache/AbstractCache.zep
  phalcon/Cache/AdapterFactory.zep
  phalcon/Cache/Cache.zep
  phalcon/Cache/CacheFactory.zep
  phalcon/Config/Config.zep
  phalcon/DataMapper/Pdo/Connection.zep
  phalcon/DataMapper/Pdo/Connection/AbstractConnection.zep
  phalcon/DataMapper/Pdo/Connection/ConnectionInterface.zep
  phalcon/DataMapper/Pdo/ConnectionLocator.zep
  phalcon/DataMapper/Pdo/Profiler/MemoryLogger.zep
  phalcon/DataMapper/Pdo/Profiler/Profiler.zep
  phalcon/DataMapper/Query/AbstractQuery.zep
  phalcon/DataMapper/Query/Bind.zep
  phalcon/DataMapper/Query/Delete.zep
  phalcon/DataMapper/Query/Insert.zep
  phalcon/DataMapper/Query/QueryFactory.zep
  phalcon/DataMapper/Query/Select.zep
  phalcon/DataMapper/Query/Update.zep
  phalcon/Di/InitializationAwareInterface.zep
  phalcon/Encryption/Security/JWT/Builder.zep
  phalcon/Encryption/Security/JWT/Token/AbstractItem.zep
  phalcon/Encryption/Security/JWT/Token/Token.zep
  phalcon/Encryption/Security/JWT/Validator.zep
  phalcon/Events/AbstractEventsAware.zep
  phalcon/Forms/Form.zep
  tests/integration/Forms/Form/ClearCest.php
Labels: bug, status: high, 5.0

#16197 Fix no recursive array value with multiple sanitizers in Filter
  phalcon/Filter/Filter.zep
  tests/unit/Filter/Filter/SanitizeMultipleCest.php
Labels: bug, status: medium, 5.0

#16204 T16202 - Escape::html zero string
  .github/workflows/main.yml
  CHANGELOG-5.0.md
  phalcon/Html/Escaper.zep
  tests/integration/Filter/Validation/ConstructCest.php
  tests/integration/Filter/Validation/ValidateCest.php
  tests/unit/Html/Escaper/HtmlCest.php
Labels: bug, status: medium, 5.0

#16230 T16223 debug links
  .github/workflows/main.yml
  CHANGELOG-5.0.md
  phalcon/Support/Debug.zep
  tests/unit/Support/Debug/GetVersionCest.php
  tests/unit/Support/Debug/RenderHtmlCest.php
Labels: bug, status: medium, 5.0

#16234 TagFactory, Profiler, Cil container fixes
  CHANGELOG-5.0.md
  phalcon/Db/Profiler.zep
  phalcon/Db/Profiler/Item.zep
  phalcon/Di/FactoryDefault/Cli.zep
  phalcon/Html/TagFactory.zep
  tests/_data/fixtures/Traits/DiTrait.php
  tests/cli/Di/FactoryDefault/Cli/ConstructCest.php
  tests/cli/Di/FactoryDefault/Cli/GetServicesCest.php
  tests/cli/Di/FactoryDefault/Cli/LoadFromPhpCest.php
  tests/cli/Di/FactoryDefault/Cli/LoadFromYamlCest.php
  tests/database/Db/Profiler/Item/GetSetFinalTimeCest.php
  tests/database/Db/Profiler/Item/GetSetInitialTimeCest.php
  tests/database/Db/Profiler/Item/GetSetSqlBindTypesCest.php
  tests/database/Db/Profiler/Item/GetSetSqlStatementCest.php
  tests/database/Db/Profiler/Item/GetSetSqlVariablesCest.php
  tests/database/Db/Profiler/Item/GetTotalElapsedNanoMicroSecondsCest.php
  tests/database/Db/Profiler/Item/GetTotalElapsedSecondsCest.php
  tests/database/Db/Profiler/ProfilerCest.php
Labels: bug, status: medium, 5.0
