Repository phalcon/cphalcon, pull requests merged in 2022-08, with the labels that each got.

#16066 #16023 - Improve object return type
  .github/workflows/main.yml
  CHANGELOG-5.0.md
  docker/7.4/.bashrc
  docker/8.0/.bashrc
  docker/8.1/.bashrc
  ext/phalcon/datamapper/pdo/connection/abstractconnection.zep.h
  ext/phalcon/datamapper/pdo/connection/connectioninterface.zep.h
  ext/phalcon/events/event.zep.c
  ext/phalcon/events/event.zep.h
  ext/phalcon/http/cookie.zep.c
  ext/phalcon/mvc/micro/lazyloader.zep.h
  ext/phalcon/support/helper/arr/toobject.zep.h
  ext/php_phalcon.h
  phalcon/Events/Event.zep
  phalcon/Tag.zep
Labels: enhancement, bug, 5.0

#16067 Fixing docblock for autocompletion
  phalcon/Html/TagFactory.zep
Labels: documentation, 5.0

#16069 T16063 implicit flush
  CHANGELOG-5.0.md
  composer.lock
  phalcon/Flash/AbstractFlash.zep
  tests/unit/Flash/Direct/OutputCest.php
Labels: bug, status: medium, 5.0

#16073 T16072 logger stream no lock
  CHANGELOG-5.0.md
  phalcon/Logger/Adapter/Stream.zep
Labels: new feature request, 5.0

#16077 Minor fixes
  composer.json
  composer.lock
  phalcon/Di/Injectable.zep
  phalcon/Mvc/View/Engine/Volt/Compiler.zep
  tests/database/Mvc/Model/Criteria/JoinCest.php
  tests/tocheck-database/Db/DbCest.php
  tests/tocheck-database/Mvc/Model/AddBehaviorCest.php
Labels: enhancement, documentation, 5.0
