Repository phalcon/cphalcon, pull requests merged in 2023-10, with the labels that each got.

#16446 T16265 getmessages array
  CHANGELOG-5.0.md
  phalcon/Mvc/Model.zep
  tests/database/Mvc/Model/GetMessagesCest.php
Labels: bug, status: medium, 5.0

#16448 MacOS 12
  .github/actions/build-phalcon-mac/action.yml
  .github/workflows/main.yml
Labels: enhancement

#16452 T16451 dm select
  CHANGELOG-5.0.md
  composer.lock
  phalcon/DataMapper/Query/Select.zep
  tests/database/DataMapper/Pdo/Profiler/MemoryLogger/LogCest.php
  tests/database/DataMapper/Pdo/Profiler/Profiler/GetSetLogLevelCest.php
Labels: bug, status: low, 5.0

#16455 T16441 tag factory reset
  .github/workflows/main.yml
  CHANGELOG-5.0.md
  phalcon/Assets/Manager.zep
  phalcon/Html/Helper/AbstractSeries.zep
  tests/integration/Mvc/View/Engine/Volt/Compiler/CompileStringCest.php
  tests/unit/Html/Helper/Link/UnderscoreInvokeCest.php
  tests/unit/Html/Helper/Meta/UnderscoreInvokeCest.php
  tests/unit/Html/Helper/Style/UnderscoreInvokeCest.php
Labels: bug, status: medium, 5.0
