Repository phalcon/cphalcon, pull requests merged in 2023-07, with the labels that each got.

#16368 #16307 - Add test case
  composer.lock
  ext/phalcon/di/injectable.zep.c
  ext/phalcon/encryption/crypt.zep.c
  ext/phalcon/storage/adapter/stream.zep.c
  ext/phalcon/storage/serializer/json.zep.c
  tests/database/Mvc/Model/FindCest.php
  tests/database/Mvc/Model/UnderscoreSetCest.php
Labels: testing, 5.0

#16369 T16244 metadata memcached
  CHANGELOG-5.0.md
  phalcon/Mvc/Model/MetaData.zep
  tests/_data/assets/schemas/mysql.sql
  tests/_data/assets/schemas/pgsql.sql
  tests/_data/assets/schemas/sqlite.sql
  tests/_data/fixtures/Migrations/AbstractMigration.php
  tests/_data/fixtures/Migrations/AlbumMigration.php
  tests/_data/fixtures/Migrations/AlbumPhotoMigration.php
  tests/_data/fixtures/Migrations/PhotoMigration.php
  tests/_data/fixtures/Traits/DiTrait.php
  tests/_data/fixtures/models/Album.php
  tests/_data/fixtures/models/AlbumPhoto.php
  tests/_data/fixtures/models/Photo.php
  tests/database/Mvc/Model/MetaData/Adapter/ReadMetadataCest.php
Labels: bug, 5.0

#16376 T16308 di dynamic properties 4
  CHANGELOG-5.0.md
  phalcon/Di/Injectable.zep
  tests/integration/Mvc/Micro/GetServiceCest.php
Labels: bug, status: medium, 5.0

#16377 added Weak Storage and Cache, for objects only using WeakReference
  CHANGELOG-5.0.md
  phalcon/Cache/Adapter/Weak.zep
  phalcon/Cache/AdapterFactory.zep
  phalcon/Storage/Adapter/Weak.zep
  phalcon/Storage/AdapterFactory.zep
  tests/integration/Cache/Adapter/ClearCest.php
  tests/integration/Cache/Adapter/ConstructCest.php
  tests/integration/Cache/Adapter/DeleteCest.php
  tests/integration/Cache/Adapter/GetAdapterCest.php
  tests/integration/Cache/Adapter/GetPrefixCest.php
  tests/integration/Cache/Adapter/GetSetCest.php
  tests/integration/Cache/Adapter/GetSetDefaultSerializerCest.php
  tests/integration/Cache/Adapter/GetSetForeverCest.php
  tests/integration/Cache/Adapter/HasCest.php
  tests/integration/Cache/Adapter/Weak/GetKeysCest.php
  tests/integration/Cache/Adapter/Weak/GetSetCest.php
  tests/integration/Cache/AdapterFactory/NewInstanceCest.php
  tests/integration/Storage/Adapter/ClearCest.php
  tests/integration/Storage/Adapter/ConstructCest.php
  tests/integration/Storage/Adapter/DeleteCest.php
  tests/integration/Storage/Adapter/GetAdapterCest.php
  tests/integration/Storage/Adapter/GetKeysCest.php
  tests/integration/Storage/Adapter/GetPrefixCest.php
  tests/integration/Storage/Adapter/GetSetCest.php
  tests/integration/Storage/Adapter/GetSetDefaultSerializerCest.php
  tests/integration/Storage/Adapter/GetSetForeverCest.php
  tests/integration/Storage/Adapter/HasCest.php
  tests/integration/Storage/AdapterFactory/NewInstanceCest.php
Labels: new feature request, 5.0

#16379 added return type for getVar() in View
  CHANGELOG-5.0.md
  phalcon/Mvc/View.zep
Labels: bug, status: medium

#16381 T15608 json last error
  CHANGELOG-5.0.md
  phalcon/Config/Adapter/Json.zep
  phalcon/DataMapper/Pdo/Profiler/Profiler.zep
  phalcon/Encryption/Security/JWT/Builder.zep
  phalcon/Encryption/Security/JWT/Token/Parser.zep
  phalcon/Http/Response.zep
  phalcon/Storage/Serializer/Json.zep
  phalcon/Support/Debug/Dump.zep
  phalcon/Support/Helper/Json/Decode.zep
  phalcon/Support/Helper/Json/Encode.zep
  tests/unit/Support/Helper/Json/DecodeCest.php
  tests/unit/Support/Helper/Json/EncodeCest.php
Labels: bug, status: medium, 5.0

#16215 T16214 delete getrelated
  phalcon/Mvc/Model.zep
  tests/_data/fixtures/Traits/CliTrait.php
  tests/database/Mvc/Model/DeleteCest.php
  tests/database/Mvc/Model/GetRelatedCest.php
  tests/unit/Di/FactoryDefault/Cli/ConstructCest.php
  tests/unit/Di/FactoryDefault/Cli/SetServiceCest.php
Labels: bug, status: high, 5.0
