Repository phalcon/cphalcon, pull requests merged in 2023-08, with the labels that each got.

#16400 Fix #16343, DynamicUpdate is now enabled system wide
  CHANGELOG-5.0.md
  config.json
  phalcon/Mvc/Model.zep
  phalcon/Mvc/Model/Manager.zep
  tests/_data/fixtures/models/CustomersDymanicUpdate.php
  tests/database/Mvc/Model/DynamicUpdateCest.php
  tests/unit/Mvc/GlobalsCest.php
Labels: bug, status: medium, 5.0

#16404 Fix memory leak in Micro
  CHANGELOG-5.0.md
  phalcon/Mvc/Micro.zep
  tests/integration/Mvc/Micro/HasServiceCest.php
  tests/integration/Mvc/Micro/OffsetExistsCest.php
Labels: bug, 5.0

#16413 Refactor & simplify Di and Service classes
  ext/phalcon/di/di.zep.c
  ext/phalcon/di/service.zep.c
  phalcon/Di/Di.zep
  phalcon/Di/Service.zep
Labels: enhancement, 5.0

#16415 T16414 route routeid type error
  .github/actions/pack-phalcon-ext/action.yml
  CHANGELOG-5.0.md
  phalcon/Mvc/Router/Route.zep
Labels: bug, status: medium, 5.0
