Repository phalcon/cphalcon, pull requests merged in 2024-01, with the labels that each got.

#16494 Removed property comments in Select Helper
  phalcon/Html/Helper/Input/Select.zep
Labels: documentation, 5.0

#16499 reworking the toarray conditionals
  phalcon/Mvc/Model.zep
Labels: bug, status: high, 5.0

#16521 Aligning Changelog
  CHANGELOG-5.0.md
  phalcon/Http/Request.zep
Labels: enhancement, 5.0
