Repository phalcon/cphalcon, pull requests merged in 2025-04, with the labels that each got.

#16745 T16741 router uri with numbers colons
  CHANGELOG-5.0.md
  phalcon/Mvc/Router.zep
  tests/integration/Mvc/Router/HandleCest.php
Labels: bug, status: medium, 5.0

#16746 Use ReflectionParameter::getType()
  CHANGELOG-5.0.md
  phalcon/Mvc/Model/Binder.zep
Labels: bug, status: medium, 5.0

#16751 Correctly match route when using query string
  CHANGELOG-5.0.md
  phalcon/Mvc/Router.zep
  tests/_data/fixtures/Mvc/Router.php
  tests/integration/Mvc/Router/ExtractRealUriCest.php
Labels: bug, status: high, 5.0

#16760 Fixing GA runs
  .github/workflows/main.yml
  composer.lock
Labels: enhancement, 5.0
