Repository phalcon/cphalcon, pull requests merged in 2025-03, with the labels that each got.

#16714 T16696 cache lifetime
  CHANGELOG-5.0.md
  phalcon/Mvc/Model/Query.zep
  phalcon/Storage/Adapter/AbstractAdapter.zep
  tests/database/Db/Column/GetScaleCest.php
  tests/database/Mvc/Model/Behavior/SoftDeleteCest.php
  tests/database/Mvc/Model/Behavior/TimestampableCest.php
  tests/database/Mvc/Model/FindCest.php
Labels: bug, status: medium, 5.0

#16715 T16713 gc iterable
  CHANGELOG-5.0.md
  phalcon/Session/Adapter/Stream.zep
  tests/_data/fixtures/Session/Adapter/StreamGlobFixture.php
  tests/integration/Session/Adapter/Stream/GcCest.php
Labels: bug, status: medium, 5.0

#16717 T16668 request basicauth
  CHANGELOG-5.0.md
  phalcon/Http/Request.zep
  tests/unit/Http/Request/GetBasicAuthCest.php
Labels: bug, status: medium, 5.0

#16718 5.9.0 prep
  .github/workflows/main.yml
  CHANGELOG-5.0.md
  composer.json
  composer.lock
  config.json
  package.xml
  phalcon/Support/Version.zep
Labels: 5.0

#16728 Add new Breadcrumbs helper component
  CHANGELOG-5.0.md
  phalcon/Html/Breadcrumbs.zep
  phalcon/Html/Helper/Breadcrumbs.zep
  phalcon/Html/TagFactory.zep
  tests/unit/Html/Helper/Breadcrumbs/AddClearRemoveToArrayCest.php
  tests/unit/Html/Helper/Breadcrumbs/GetSetClearAttributesCest.php
  tests/unit/Html/Helper/Breadcrumbs/GetSetSeparatorCest.php
  tests/unit/Html/Helper/Breadcrumbs/GetSetTemplateCest.php
  tests/unit/Html/Helper/Breadcrumbs/RenderCest.php
Labels: new feature request, enhancement, 5.0

#16731 Changing build extension php to 8.4
  .github/workflows/main.yml
Labels: enhancement, 5.0
